### ISSUE TITLE
White border on fullscreen

### ISSUE THREAD

**Issue by ichirou2910** [Fmstrat/winapps#102]
Hi, thanks for creating winapps. So far I'm very satisfied with it. But there are some issues. Idk if I can put multiple issues here since there is only one title but I will put this one first.
So this is Word app running normally
![image](https://user-images.githubusercontent.com/51302893/100064987-cc5aa800-2e65-11eb-9428-ff870493bae7.png)
But when I click on maximize button, there is a white border wrapping around the window
![image](https://user-images.githubusercontent.com/51302893/100065059-e5fbef80-2e65-11eb-95d9-f1363d0f33c0.png)
Is there any way to remove the border?

**Comment by Fmstrat** [comment]
Unfortunately this a FreeRDP issue, so you would need to open the same issue there. If you do, please link this issue, thanks!

**Comment by jobs-git** [comment]
Fixed in freerdp 2.3.2
