### ISSUE TITLE
Unsupported configuration

### ISSUE THREAD

**Issue by TheusFacin** [Fmstrat/winapps#104]
Hello

When I try to run `bin/winapps check`, the prompt gives me the following message. 
```
❯ bin/winapps check
RDPWindows is not running, run:
  virsh start RDPWindows
```
But, when I try it, it gives an error saying:
```
❯ virsh start RDPWindows   
error: Failed to start domain RDPWindows
error: unsupported configuration: Security driver model 'dac' is not available
```
The virtual machine is working properly, with my apps installed and all configurations done, according the guide.
Can someone help me?

**Comment by TheusFacin** [comment]
Well, I fixed it. I mixed up some users configurations and used sudo in places I shouldn't. I defined RDPWindows without using sudo and it gone well. Thanks anyway

**Comment by bphd** [comment]
Some other solutions:
https://github.com/Fmstrat/winapps/issues/173#issuecomment-854093497
https://github.com/Fmstrat/winapps/issues/9#issuecomment-723592536
