### ISSUE TITLE
Outlook ETA

### ISSUE THREAD

**Issue by JayDoubleu** [Fmstrat/winapps#11]
Any ETA on outlook? In my case that's the most wanted app I would like to bring to my Linux machine.

Thanks,

**Comment by Fmstrat** [comment]
Can you try the outlook branch? https://github.com/Fmstrat/winapps/tree/outlook

Everything looks right but I haven't tested it yet. You can just run `./install.sh` again if you have already configured applications.

**Comment by Tiebe** [comment]
Outlook 365 works. I suppose we can close this now?

**Comment by Fmstrat** [comment]
Yup
