### ISSUE TITLE
Failed to get network 'default'

### ISSUE THREAD

**Issue by Kwbmm** [Fmstrat/winapps#126]
Hello!
I have attempted using `winapps` with Manjaro and am experiencing some issues, namely, the `check` fails with the following error:
```bash
error: failed to get network 'default'
error: Network not found: no network with matching name 'default'
[00:57:32:989] [9921:9922] [INFO][com.freerdp.core] - freerdp_connect:freerdp_set_last_error_ex resetting error state
[00:57:32:989] [9921:9922] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[00:57:32:989] [9921:9922] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[00:57:32:989] [9921:9922] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[00:57:32:989] [9921:9922] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rail
[00:57:32:989] [9921:9922] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
[00:57:33:302] [9921:9922] [INFO][com.freerdp.primitives] - primitives autodetect, using optimized
[00:57:33:309] [9921:9922] [ERROR][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex ERRCONNECT_DNS_NAME_NOT_FOUND [0x00020005]
```
I believe the problem is the configuration of the network:

![image](https://user-images.githubusercontent.com/8115374/100528536-6318c300-31de-11eb-81fa-6fcbde88e715.png)

The thing is that, during setup, I could not choose `Virtual network 'default': NAT` as show in the installation picture:
![image](https://user-images.githubusercontent.com/8115374/100528592-036ee780-31df-11eb-962d-4b662aa344b8.png)

Any pointer on how I can connect through RDP with networking in usermode?

**Comment by Matige** [comment]
Was the virtual machine created in user session mode? Paste the result of the following commands:
`virsh uri`
`virsh -c qemu:///system list --all`
`virsh -c qemu:///session list --all`
`virsh net-list --all --inactive`

**Comment by Kwbmm** [comment]
Yes, the VM was created in usermode. I have noticed that if I run `virt-manager` as root, I can get away from usermode. Having said that, I didn't find out how to do the same. Will test the changes in #13

**Comment by Kwbmm** [comment]
I'm not sure #13 has helped or not, but I get a different problem, way before in the script, so that was a regression. But I'm not sure the change is related to that. Either way, I now get:
```
RDPWindows is not running, run:
  virsh start RDPWindows
```

Which is (of course) false. If I run `virsh start RDPWindows`, I get `error: failed to get domain 'RDPWindows'`

In the next days I will attempt to remove everything and start from scratch again and follow #78 to see if anything changes.

But anyway, back to the original issue, I saw that running `virt-manager` as root, makes the nat appear and I'm confident that by doing the install as root, things are going to work, but I would like to avoid this and haven't found how yet.

This is the output of `virsh uri` (after having done the change from #13 ): `qemu:///system`

`virsh -c qemu:///system list --all` returns an empty table.

`virsh -c qemu:///session list --all` returns:
```
 Id   Name         State
----------------------------
 3    RDPWindows   running
```

And `virsh net-list --all --inactive`:

```
 Name      State      Autostart   Persistent
----------------------------------------------
 default   inactive   no          yes
```

**Comment by Matige** [comment]
Your default connection URI is now `qemu:///system`, but the virtual machine was created in `qemu:///session`. You can run it with the `virsh -c qemu:///session start RDPWindows` command. This does not matter, however, because the virtual machines in the user session do not have access to the network bridge. You can try using [qemu-bridge-helper](https://wiki.qemu.org/Features/HelperNetworking) or create a virtual machine in `qemu:///system`.

**Comment by Kwbmm** [comment]
Partially following #78 (until [this](https://github.com/Fmstrat/winapps/pull/78/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R164) point) and going back [here](https://github.com/Fmstrat/winapps/blob/main/docs/KVM.md) for the installation, I managed to make it work.

Thanks for the pointers!

**Comment by ittisafur** [comment]
My problem is the same i have configured exactly the way it was told.
I am using user session mode and when i created the VM i was connected to the user session mode.
Then i changed the IP in the winapps.conf file and running `LIBVIRT_DEFAULT_URI=qemu:///session ./winapps check` gives me the following
![image](https://ibb.co/dPtCKkQ)
My IP for the VM
![image](https://ibb.co/9N624kN)

**Comment by lusmo** [comment]
Hello,
First of all, thank you very much for your work on winapps!
I tried to implement the solution in Fedora, but I ran into the same problem that I need help with:

**The first command runs correctly:**
```
virsh start RDPWindows
Domain "RDPWindows" started
```

**But later:**

```
bin/winapps check
error: failed to get network "default"
error: Network not found: no network with matching name 'default'
[13:28:15:173] [10636:10643] [ERROR][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex ERRCONNECT_DNS_NAME_NOT_FOUND [0x00020005]

```
I've searched everywhere I can, I've tried using the procedures I've found, but I can't figure out how to proceed.

Thank you for your help!

**Comment by YeesterPlus** [comment]
`/usr/share/libvirt/networks/default.xml` 
```
<network>
    <name>default</name>
    <forward mode='nat'>
        <nat>
            <port start='1024' end='65535' />
        </nat>
    </forward>
    <bridge name='virbr0' stp='on' delay='0' />
    <ip address='192.168.122.1' netmask='255.255.255.0'>
        <dhcp>
            <range start='192.168.122.2' end='192.168.122.254' />
        </dhcp>
    </ip>
</network>
```
then run
```
virsh net-define /usr/share/libvirt/networks/default.xml
virsh net-autostart default
sudo virsh net-start default 
```

**Comment by YeesterPlus** [comment]
and use windows settings to get the ip addr and use RDPWINDOWS as the domain
