### ISSUE TITLE
Applications Not Opening When Using Shortcuts

### ISSUE THREAD

**Issue by xeu100** [Fmstrat/winapps#160]
Just as the title says, when i use the installed shortcuts for anything, they don't do anything. I can run the commands they specify and they work, but the shortcuts don't. I'm using Fedora 33 with Gnome (wayland).

**Comment by xeu100** [comment]
Issue was with zsh and virsh flags

**Comment by nysascape** [comment]
Hi there, I'm having this issue, what was it exactly you did to solve it?

**Comment by luoiliembac** [comment]
Hi, this sound similar to my issue #180 .
Could you please let me know how to solve it?

> Issue was with zsh and virsh flags

**Comment by xeu100** [comment]
The issue is not permission-related, and my issue was unique because of my setup. As I was using zsh, my virsh was set to use the user one by default, not the system one (where my windows 10 VM was setup), so I had to modify my environment variables.

**Comment by nysascape** [comment]
> The issue is not permission-related, and my issue was unique because of my setup. As I was using zsh, my virsh was set to use the user one by default, not the system one (where my windows 10 VM was setup), so I had to modify my environment variables.

I'm using zsh too on Arch, would you mind telling me how to bump it into system mode using environment vars?

**Comment by MattKowalskii** [comment]
I am having a similar issue on Pop_os! using zsh, can't launch the .desktop shortcuts

**Comment by xeu100** [comment]
To be honest, it's been a long time since I've done it so I'm unsure, that and the installation I did it on is no longer installed.

**Comment by luoiliembac** [comment]
> To be honest, it's been a long time since I've done it so I'm unsure, that and the installation I did it on is no longer installed.

Could you please give us some related links so that we can do it ourselves? I also use zsh, but totally don't what to do (newbie to Linux).
Thank you very much!

**Comment by AlexDias95** [comment]
I have the same problem, can you help? I am using Fedora 33 too
