### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by nobodywasishere** [Fmstrat/winapps#17]
Could you add a specific license to the project?

**Comment by connlim** [comment]
Yes please add a license to this project, otherwise it is basically proprietary software and would limit possible contributions. I personally recommend the AGPLv3.

**Comment by Fmstrat** [comment]
Good call, will pick out my license once all the traffic settles down and I get a few minutes to think. Will likely be GPL. Thanks!

**Comment by nobodywasishere** [comment]
The only thing I'm worried about with this is the icons for the applications themselves, as I don't know if you've used the ones directly from Microsoft (and thus those icons aren't ours to put under GPL). Maybe it's worth looking into icon packs that are available under permissive or copyleft licenses alongside adding a license to this project?

**Comment by Fmstrat** [comment]
> The only thing I'm worried about with this is the icons for the applications themselves

This is a really good point. While I doubt MS would care since it's merely a shortcut, I see two solutions here:
1. Swap icons to a GPL set
2. (Preferred) Find a way to extract an SVG icon from the Windows executable

I'm going to investigate the latter before licensing.

**Comment by Fmstrat** [comment]
@nobodywasishere Any idea if an MIT license on FluentUI would allow me to use the data for the SVG from: https://github.com/microsoft/fluent-ui-react/blob/774b9f2c5f1770c08ab996aade336a27060a0475/packages/react/src/themes/teams/components/Icon/svg/ProcessedIcons/icons-msft-xl.tsx ?

FluentUI includes the office icons.

**Comment by Fmstrat** [comment]
Hmm, looks good. As per: https://static2.sharepointonline.com/files/fabric/assets/microsoft_fabric_assets_license_agreement_nov_2019.pdf

> License  Grant.  Microsoft  grants  to  Developer,  a  non-exclusive,  revocable,  worldwide,  non-assignable,  non-transferable,  royalty-free  license  to  use  the  Fabric  Assets  (defined  below)  or  a subset of them (e.g. the ‘Toolkit’) exclusively for the following purposes: a.In  connection  with  the  use  of  a  Microsoft  API  within  the  development  of  a  software application, website, or product you create or a service you offer designed to provide access or interact with a Microsoft service or application (“Application”) b.Toillustrate that Application integrates with one or more Microsoft products and services.

**Comment by nobodywasishere** [comment]
That looks good to me.

**Comment by jtojnar** [comment]
> once all the traffic settles down

Note that you also need agreement of all the code contributors to change the license so it is better to do it sooner than later, while there are only few of them.

**Comment by Croydon** [comment]
Why was this closed as not planned?

**Comment by nobodywasishere** [comment]
Didn't want to leave an issue open that wouldn't get resolved.
