### ISSUE TITLE
error with hardcoded vm name

### ISSUE THREAD

**Issue by x0rld** [Fmstrat/winapps#177]
I don't understand why the vmname is hardcoded 
https://github.com/Fmstrat/winapps/blob/f2ce9a557b488746fd3ecde194cd900a554e2b1c/bin/winapps#L57

**Comment by stuaxo** [comment]
I'd also like to be able to specify this.

My existing Windows vm is 80gb, and I don't have enough space on my SSD for another.
virt-manager doesn't seem to want to let me rename it either.

**Comment by BasicWombat** [comment]
> virt-manager doesn't seem to want to let me rename it either.

I'm only new to KVM but does this work?
https://serverfault.com/questions/203311/how-to-rename-a-vm-using-libvirtkvm

**Comment by x0rld** [comment]
it looks like you export the config in xml then import it in a new vm

**Comment by stuaxo** [comment]
Did it work @x0rld I'm not sure I want to risk my Windows VM.
I also have snapshots, and I think some of the solutions said they won't work with snapshots.

**Comment by x0rld** [comment]
I didn't test, you can clone your vm and try on the clone to be sure

**Comment by stuaxo** [comment]
I stopped using winapps when I worked out my issue with Linux teams (it was getting in a boot loop, but just due to using a wrong work login).

This seems like it would be good as a PR.
