### ISSUE TITLE
Can't pass 'bin/winapps check'

### ISSUE THREAD

**Issue by Dev0110** [Fmstrat/winapps#183]
Hello,
I can't successfully run the command 'bin/winapps check'. It doesn't run without sudo rights...
Here's the full output (both without and with sudo rights) :

- mc2@MERCURE:~/winapps$ bin/winapps check
- RDPWindows is not running, run:
-   virsh start RDPWindows
- mc2@MERCURE:~/winapps$ sudo bin/winapps check
- [14:54:59:234] [7729:7730] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
- [14:54:59:234] [7729:7730] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
- [14:54:59:234] [7729:7730] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
- [14:54:59:234] [7729:7730] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rail
- [14:54:59:234] [7729:7730] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
- [14:54:59:553] [7729:7730] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
- [14:54:59:553] [7729:7730] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
- [14:54:59:559] [7729:7730] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
- [14:54:59:560] [7729:7739] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service drive [home] (static)
- [14:54:59:560] [7729:7740] [INFO][com.freerdp.channels.rdpsnd.client] - Loaded fake backend for rdpsnd
- [14:54:59:560] [7729:7730] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel disp
- [14:55:02:762] [7729:7730] [INFO][com.freerdp.client.x11] - Logon Error Info SESSION_ID [LOGON_MSG_SESSION_CONTINUE]
- [14:55:05:718] [7729:7739] [INFO][com.freerdp.channels.rdpdr.client] - registered device #1: home (type=8 id=1)
- [14:55:31:384] [7729:7743] [ERROR][com.freerdp.client.x11] - RAIL exec error: execResult=RAIL_EXEC_E_FAIL NtError=0x2
- 
- [14:55:31:384] [7729:7730] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
- [14:55:31:384] [7729:7730] [INFO][com.freerdp.client.common] - Network disconnect!
- [14:55:31:384] [7729:7730] [INFO][com.freerdp.client.common] - Attempting reconnect (1 of 20)
- [14:55:31:928] [7729:7730] [INFO][com.freerdp.core] - ERRINFO_DISCONNECTED_BY_OTHER_CONNECTION (0x00000005):Another user connected to the server, forcing the disconnection of the current connection.
- [14:55:31:928] [7729:7730] [INFO][com.freerdp.core] - ERRINFO_DISCONNECTED_BY_OTHER_CONNECTION (0x00000005):Another user connected to the server, forcing the disconnection of the current connection.
- [14:55:36:937] [7729:7730] [INFO][com.freerdp.client.common] - Attempting reconnect (2 of 20)
- [14:55:36:217] [7729:7783] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service drive [home] (static)
- [14:55:36:217] [7729:7784] [INFO][com.freerdp.channels.rdpsnd.client] - Loaded fake backend for rdpsnd
- [14:55:36:217] [7729:7730] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel disp
- [14:55:37:140] [7729:7783] [INFO][com.freerdp.channels.rdpdr.client] - registered device #1: home (type=8 id=1)
- [14:55:45:525] [7729:7786] [ERROR][com.freerdp.client.x11] - RAIL exec error: execResult=RAIL_EXEC_E_FAIL NtError=0x2
- 
- [14:55:45:525] [7729:7730] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
- [14:55:45:525] [7729:7730] [INFO][com.freerdp.client.common] - Network disconnect!
- [14:55:45:525] [7729:7730] [INFO][com.freerdp.client.common] - Attempting reconnect (1 of 20)
- [14:55:45:062] [7729:7730] [INFO][com.freerdp.core] - ERRINFO_DISCONNECTED_BY_OTHER_CONNECTION (0x00000005):Another user connected to the server, forcing the disconnection of the current connection.
- [14:55:45:062] [7729:7730] [INFO][com.freerdp.core] - ERRINFO_DISCONNECTED_BY_OTHER_CONNECTION (0x00000005):Another user connected to the server, forcing the disconnection of the current connection.
- [14:55:50:070] [7729:7730] [INFO][com.freerdp.client.common] - Attempting reconnect (2 of 20)
- [14:55:51:289] [7729:7805] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service drive [home] (static)
- [14:55:51:289] [7729:7806] [INFO][com.freerdp.channels.rdpsnd.client] - Loaded fake backend for rdpsnd
- [14:55:51:289] [7729:7730] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel disp
- [14:55:51:193] [7729:7805] [INFO][com.freerdp.channels.rdpdr.client] - registered device #1: home (type=8 id=1)
- [14:55:57:608] [7729:7730] [INFO][com.freerdp.core] - ERRINFO_LOGOFF_BY_USER (0x0000000C):The disconnection was initiated by the user logging off their session on the server.
- mc2@MERCURE:~/winapps$

**Comment by xiagw** [comment]
> Hello,
> I can't successfully run the command 'bin/winapps check'. It doesn't run without sudo rights...
> Here's the full output (both without and with sudo rights) :
> 
>     * mc2@MERCURE:~/winapps$ bin/winapps check
> 
>     * RDPWindows is not running, run:
> 
>     * virsh start RDPWindows
> 
>     * mc2@MERCURE:~/winapps$ sudo bin/winapps check
> 
>     * [14:54:59:234] [7729:7730] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
> 
>     * [14:54:59:234] [7729:7730] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
> 
>     * [14:54:59:234] [7729:7730] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
> 
>     * [14:54:59:234] [7729:7730] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rail
> 
>     * [14:54:59:234] [7729:7730] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
> 
>     * [14:54:59:553] [7729:7730] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
> 
>     * [14:54:59:553] [7729:7730] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
> 
>     * [14:54:59:559] [7729:7730] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
> 
>     * [14:54:59:560] [7729:7739] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service drive [home] (static)
> 
>     * [14:54:59:560] [7729:7740] [INFO][com.freerdp.channels.rdpsnd.client] - Loaded fake backend for rdpsnd
> 
>     * [14:54:59:560] [7729:7730] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel disp
> 
>     * [14:55:02:762] [7729:7730] [INFO][com.freerdp.client.x11] - Logon Error Info SESSION_ID [LOGON_MSG_SESSION_CONTINUE]
> 
>     * [14:55:05:718] [7729:7739] [INFO][com.freerdp.channels.rdpdr.client] - registered device #1: home (type=8 id=1)
> 
>     * [14:55:31:384] [7729:7743] [ERROR][com.freerdp.client.x11] - RAIL exec error: execResult=RAIL_EXEC_E_FAIL NtError=0x2
> 
>     * [14:55:31:384] [7729:7730] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
> 
>     * [14:55:31:384] [7729:7730] [INFO][com.freerdp.client.common] - Network disconnect!
> 
>     * [14:55:31:384] [7729:7730] [INFO][com.freerdp.client.common] - Attempting reconnect (1 of 20)
> 
>     * [14:55:31:928] [7729:7730] [INFO][com.freerdp.core] - ERRINFO_DISCONNECTED_BY_OTHER_CONNECTION (0x00000005):Another user connected to the server, forcing the disconnection of the current connection.
> 
>     * [14:55:31:928] [7729:7730] [INFO][com.freerdp.core] - ERRINFO_DISCONNECTED_BY_OTHER_CONNECTION (0x00000005):Another user connected to the server, forcing the disconnection of the current connection.
> 
>     * [14:55:36:937] [7729:7730] [INFO][com.freerdp.client.common] - Attempting reconnect (2 of 20)
> 
>     * [14:55:36:217] [7729:7783] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service drive [home] (static)
> 
>     * [14:55:36:217] [7729:7784] [INFO][com.freerdp.channels.rdpsnd.client] - Loaded fake backend for rdpsnd
> 
>     * [14:55:36:217] [7729:7730] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel disp
> 
>     * [14:55:37:140] [7729:7783] [INFO][com.freerdp.channels.rdpdr.client] - registered device #1: home (type=8 id=1)
> 
>     * [14:55:45:525] [7729:7786] [ERROR][com.freerdp.client.x11] - RAIL exec error: execResult=RAIL_EXEC_E_FAIL NtError=0x2
> 
>     * [14:55:45:525] [7729:7730] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
> 
>     * [14:55:45:525] [7729:7730] [INFO][com.freerdp.client.common] - Network disconnect!
> 
>     * [14:55:45:525] [7729:7730] [INFO][com.freerdp.client.common] - Attempting reconnect (1 of 20)
> 
>     * [14:55:45:062] [7729:7730] [INFO][com.freerdp.core] - ERRINFO_DISCONNECTED_BY_OTHER_CONNECTION (0x00000005):Another user connected to the server, forcing the disconnection of the current connection.
> 
>     * [14:55:45:062] [7729:7730] [INFO][com.freerdp.core] - ERRINFO_DISCONNECTED_BY_OTHER_CONNECTION (0x00000005):Another user connected to the server, forcing the disconnection of the current connection.
> 
>     * [14:55:50:070] [7729:7730] [INFO][com.freerdp.client.common] - Attempting reconnect (2 of 20)
> 
>     * [14:55:51:289] [7729:7805] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service drive [home] (static)
> 
>     * [14:55:51:289] [7729:7806] [INFO][com.freerdp.channels.rdpsnd.client] - Loaded fake backend for rdpsnd
> 
>     * [14:55:51:289] [7729:7730] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel disp
> 
>     * [14:55:51:193] [7729:7805] [INFO][com.freerdp.channels.rdpdr.client] - registered device #1: home (type=8 id=1)
> 
>     * [14:55:57:608] [7729:7730] [INFO][com.freerdp.core] - ERRINFO_LOGOFF_BY_USER (0x0000000C):The disconnection was initiated by the user logging off their session on the server.
> 
>     * mc2@MERCURE:~/winapps$

**### RDPWindows is not running, run:
virsh start RDPWindows**

**Comment by bjnobre** [comment]
I've experiencing the same issue (RDPWindows is not running). I have remote desktop enabled (I can connect directly via xfreerdp command). I've tried to run as a sudo but I got the same error.
If I run "virsh start RDPWindows" I got the error "error: failed to get domain 'RDPWindows'"
