### ISSUE TITLE
Can't use Taskbar after one app was opened

### ISSUE THREAD

**Issue by shhkid** [Fmstrat/winapps#19]
Hi,
after  I opened one app, e.g. Outlook, I can't use the taskbar anymore. Seems that the VM is overlaying it.
My taskbar in on the bottom, like in Windows.
Regards,
Shhkid

**Comment by Fmstrat** [comment]
I'm not sure I follow the issue here. Could you post a screenshot or GIF from Peek?

**Comment by shhkid** [comment]
![Peek 2020-11-09 14-51](https://user-images.githubusercontent.com/55892034/98549707-7994c400-229b-11eb-8371-e76a69cc0de4.gif)


The bottom area in the taskbar isn't clickable.

Additionally my VM isn't starting on system start (autostart option is set). Anything else I can do about it?

**Comment by Fmstrat** [comment]
Well that's something I haven't seen before. Can you provide some system details? OS? Extensions? Is that Dash to Panel?

As for system start, I'm not sure. Is libvirt starting up as a service?

**Comment by shhkid** [comment]
Linux Mint 20 (ulyana), Theme: Vimix.
Nope not dash to panel, default Mint behaviour I guess.

Thanks for the tip, I enabled libvirtd service. let's see if it helps.

**Comment by shhkid** [comment]
Update:
I changed the position of the Taskbar to top, but unfortunately it's still not clickable. Really strange.

**Comment by Fmstrat** [comment]
If you don't use fullscreen, does it still keep the taskbar from being clickable?

**Comment by shhkid** [comment]
The window size doesn't matter. I just figured out that it works when Cinnamon is in fallback mode. Will have to check the cinnamon logs if something crashes when opening a VM window.

**Comment by Fmstrat** [comment]
Oh good find. Let me know how it goes!

**Comment by shhkid** [comment]
Only this warning in the cinnamon log... 
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested)

**Comment by Fmstrat** [comment]
Looks like this is a downstream issue: https://github.com/FreeRDP/FreeRDP/issues/6130
