### ISSUE TITLE
secure winapps.conf file 

### ISSUE THREAD

**Issue by DennisVozian** [Fmstrat/winapps#190]
if we set a password to the winapps.conf file, how do we tell the RDP to access the file using the password? right now the credentials for the RDPWindows machine are exposed in clear text if you go to that file, would be good to be able to secure that with a password or encryption of some sort.

**Comment by IntinteDAO** [comment]
The question is whether this is necessary. In theory, you should use WinApps on a local computer with a local virtual machine. So the security of such a machine need not be powerful.
