### ISSUE TITLE
RDPWindows is not running: even though it is

### ISSUE THREAD

**Issue by vinicius507** [Fmstrat/winapps#199]
Greetings,

following the tutorial to set up KVM and Winapps, this happens:

```sh
$ bin/winapps check
RDPWindows is not running, run:
  virsh start RDPWindows
```

If I try to list domains, this happens:
```sh
$ virsh list --all
 Id   Name   State
--------------------

```

But if I use:
```sh
$ virsh --connect qemu:///system list
 Id   Name         State
----------------------------
 3    RDPWindows   running
```

I don't know what this means and how I can solve it

**Comment by vinicius507** [comment]
Solved. Setting `LIBVIRT_DEFAULT_URI`  to `qemu:///system` makes it work.

**Comment by JasperEdits** [comment]
I have the same output for `$ virsh --connect qemu:///system list`, and setting that variable doesn't seem to do an effect.
Are you supposed to do `LIBVIRT_DEFAULT_URI=qemu:///system` in the terminal?

**Comment by vinicius507** [comment]
> I have the same output for `$ virsh --connect qemu:///system list`, and setting that variable doesn't seem to do an effect.
> Are you supposed to do `LIBVIRT_DEFAULT_URI=qemu:///system` in the terminal?

Yes. Run it like this:

```bash
LIBVIRT_DEFAULT_URI=qemu:///system bin/winapps check
```

**Comment by JasperEdits** [comment]
That resets on system reboot, I had to place it under `/etc/enviromental` (`export LIBVIR...`).
Now the programs appear in the desktop, but don't open up, but If I go to the respective .desktop file and execute the `exec` it works, weird.

**Comment by vinicius507** [comment]
You're running the applications using the check command? That's only used to verify if it's working. Run the install script with the same variable and it'll work. No need to place it as a permanent ENV variable..

**Comment by chesterbelle** [comment]
im having the same issue  using this 
LIBVIRT_DEFAULT_URI=qemu:///system bin/winapps check works
 but  i dont know how to install i mean how can i   Run the install script with the same variable ?

**Comment by bjnobre** [comment]
I've got the same error (RDPWindows is not running), even when I'm running with the LIBVIRT_DEFAULT_URI parameter!
