### ISSUE TITLE
Cannot resize windows

### ISSUE THREAD

**Issue by jonchampagne** [Fmstrat/winapps#2]
This may be an issue with xfreerdp, but I seem completely unable to resize any app windows. I'm simply not getting the handle at the edges or corners to resize the windows.

**Comment by Fmstrat** [comment]
Yes, this is an issue with FreeRDP. You actually can resize, it's just that the handle cursor doesn't show up, and the window doesn't resize as your dragging. These are some issues I'd like to work out with the RDP team (including reuse of connection on second app start, vs reconnect).

**Comment by c0lp4nik** [comment]
This is a fabulous app. Hello VM**** Fusion for Linux! 

Only have 1 issue, also need to pass /dynamic-resolution /scale:180  (for me, I have High Res monitors which I'm sure a lot do! These two switches mean the world! Resize-able window, check! Fonts readable - check! If you can pass those along on your xfreerdp CLI, you're golden. I added it to the install.sh but it only worked for initial setup :(.  Thanks and hope you can add these 2 switches for tall the apps!

**Comment by Fmstrat** [comment]
@c0lp4nik  Can you open that as a separate issue?

**Comment by c0lp4nik** [comment]
No problem.

**Comment by c0lp4nik** [comment]
adding /dynamic-resolution to the xfreerdp CLI for all apps will solve the problem above....or should solve it, hopefully.

**Comment by Fmstrat** [comment]
https://github.com/Fmstrat/winapps/commit/d05bf48d627193c501d96cbaa5a4671fb20d7f9d

**Comment by Tiebe** [comment]
Any update on the original issue here?
