### ISSUE TITLE
Question: How much storage and ram is required?

### ISSUE THREAD

**Issue by rushic24** [Fmstrat/winapps#231]
I have only 8Gigs of ram laptop and 128GB ssd with Arch linux. 
I had used kvm before with windows10 virtual machine and it lagged heavily. Does this use same windows 10 iso or its compact?

**Comment by koriwi** [comment]
it uses windows 10 pro provided by microsoft. i would say 4gb is the bare minimum you would want to give to the vm depending on what you are doing. But you could try to slim down the installation after you set it up. there are many guides out there how to debloat windows 10

**Comment by rushic24** [comment]
Just tried, I think it'll need like 70-80GB of storage at least to keep apps like Office and Photoshop all installed
