### ISSUE TITLE
Can winapps run wechat ?

### ISSUE THREAD

**Issue by ZCDu** [Fmstrat/winapps#233]
How can winapps run other apps not in the recommended list.

**Comment by xiagw** [comment]
yes, 
qq, wechat , work wechat ...

**Comment by dongdongbh** [comment]
here is the my wechat config for `apps/wechat/info`
```
# GNOME shortcut name
NAME="Wechat"

# Used for descriptions and window class
FULL_NAME="Wechat"

# The executable inside windows
WIN_EXECUTABLE="C:\Program Files\Tencent\Wechat\Wechat.exe"

# GNOME categories
CATEGORIES="WinApps;Windows"

# GNOME mimetypes
MIME_TYPES=""
```

`icon.svg` can be found [here](https://www.logo.wine/logo/WeChat)

**Comment by DongshengHuang** [comment]
Is there a black border after running?

**Comment by dongdongbh** [comment]
> Is there a black border after running?
> […](#)
> On Nov 30, 2022, at 16:43, Dontae ***@***.***> wrote: ﻿ here is the my wechat config for apps/wechat/info # GNOME shortcut name NAME="Wechat" # Used for descriptions and window class FULL_NAME="Wechat" # The executable inside windows WIN_EXECUTABLE="C:\Program Files\Tencent\Wechat\Wechat.exe" # GNOME categories CATEGORIES="WinApps;Windows" # GNOME mimetypes MIME_TYPES="" icon.svg can be found here — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

Yes, I geuss it relates to Wechat since Office apps don't have this issue.

**Comment by xTayEx** [comment]
wechat sucks. word and powerpoint run well using winapps. wechat cracks again and again! f**k u tencent!

**Comment by xusos** [comment]
现在 QQ 微信都有linux版了

**Comment by xusos** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
