### ISSUE TITLE
Access audio device from Winapps

### ISSUE THREAD

**Issue by andersonpem** [Fmstrat/winapps#239]
I'm trying to use the dictation features from Microsoft Office. But it seems they don't work using Winapps.
Is it a limitation from the RDP use, or is it doable in some form?

Thanks guys.

**Comment by RGFTheCoder** [comment]
In the options part of the readme file: 

"To add flags to the FreeRDP call, such as /audio-mode:1 to pass in a mic, use the RDP_FLAGS configuration option"

Though I haven;t played around with it
