### ISSUE TITLE
[Suggestion] Use "${HOME}/.local/share/applications/" instead of the system "/usr/share/applications/"

### ISSUE THREAD

**Issue by zacmks** [Fmstrat/winapps#27]
To keep the system installation clean, and to not override/conflict with applications installed on the host machine.

Not with current supported apps, but there are several programs that exists on Windows and Linux.

E.g.: Filezilla, vlc, firefox, audacity, vscode, etc...

**Comment by Fmstrat** [comment]
You must have cloned right when I released as this is already the case ;)

**Comment by Fmstrat** [comment]
Apologies, I have not yet merged this.

**Comment by Fmstrat** [comment]
Complete with new installer.
