### ISSUE TITLE
If the project is Stale for 10 months, should a maintained fork be created?

### ISSUE THREAD

**Issue by luciorq** [Fmstrat/winapps#273]
This project has demonstrated value and interest from the community.

It is relevant to point that it has already attracted media outlets and attention outside of the development community.

If there isn't any maintained fork yet, I would say that **it is probably already time for an open-source organization to fork and maintain**.

Anyone can recommend a good organization focused on desktop integrity, that ideally, the original authors could also be part if they want to further maintain the project?

**Comment by adil192** [comment]
See #269

**Comment by luciorq** [comment]
Thanks for pointing me this

**Comment by luciorq** [comment]
I will close this issue as most important topic is already being discussed in the issue #263.
