### ISSUE TITLE
Black screen on winapps windows

### ISSUE THREAD

**Issue by TeaSpillStudios** [Fmstrat/winapps#297]
I am on Zorin OS. Is there an help I could get, my issue is that if I start an applications, first of all photoshop and illustrator don't work. Creative cloud will launch but has a black screen. Same with cmd and powershell, etc. But in a certain position, sometimes I will see parts of a window. But I will have a huge black box around it

For example, here
![image](https://user-images.githubusercontent.com/57747851/145484669-73f1b125-5fe6-45a6-9eef-cdbbb7ccba6e.png)

And also, alot of the times the windows will be black no matter what, I have also had windows glide across screens and get smaller when moved. Any help would be greatly appreciated

**Comment by Benmac83** [comment]
I will update the status of what happens here! Please ask if you need any more information

**Comment by Benmac83** [comment]
Just to confirm, this is a fully paid for version of CC, it is not pirated and so it is official software, and so should supposedly be supported by winapps

**Comment by NyleCohen** [comment]
Can you show the contents of your `~/.config/winapps/winapps.conf`?

**Comment by Benmac83** [comment]
Hi, sorry for the huge delay, my OS died and I'm on arch at the moment, currently trying to get it working on arch!

**Comment by Benmac83** [comment]
Hey there!
![image](https://user-images.githubusercontent.com/57747851/146468847-46f6d34c-6614-41b1-ad92-24cb2af213fb.png)

I've nearly got things working but this is the only thing standing in my way. I hope you and this can help!

**Comment by Benmac83** [comment]
My winapps config is as follows:

RDP_USER="RDPWindows"
RDP_PASS="<NOT HERE FOR MY SAFETY>"
RDP_DOMAIN="RDPWindows"

**Comment by TarouShota** [comment]
@TeaSpillStudios 
did u give up on this?
