### ISSUE TITLE
Resolution for High Res Displays and Scroll-able windows

### ISSUE THREAD

**Issue by c0lp4nik** [Fmstrat/winapps#34]
This is a fabulous app. Hello VM**** Fusion for Linux! 

Only have 1 issue, also need to pass /dynamic-resolution /scale:180  (for me, I have High Res monitors which I'm sure a lot do! These two switches mean the world! Resize-able window, check! Fonts readable - check! If you can pass those along on your xfreerdp CLI, you're golden. I added it to the install.sh but it only worked for initial setup :(.  Thanks and hope you can add these 2 switches for all the apps! I.e. xfreerdp /u:"${RDP_USER}" /p:"${RDP_PASS}" /v:${RDP_IP} **_/dynamic-resolution /scale:180_** +auto-reconnect +home-drive -wallpaper /span /wm-class etc.. etc..

**Comment by Fmstrat** [comment]
Interesting, dynamic-resolution isn't supposed to do anything in apps, just in a full RDP session (which I had already included it for). Adding it to apps has no impact for me, but if it does for others, I will include it.

**Comment by Fmstrat** [comment]
https://github.com/Fmstrat/winapps/commit/d05bf48d627193c501d96cbaa5a4671fb20d7f9d

**Comment by c0lp4nik** [comment]
Thanks for this! Keep up the great work on this project!

**Comment by c0lp4nik** [comment]
I can re-size the window(s) now, Good! But font remains super-small.  /scale:180 helps with my other freeRDP, but is needed here still...thoughts?

**Comment by Fmstrat** [comment]
@c0lp4nik `RDP_SCALE` is an option.

**Comment by c0lp4nik** [comment]
Can you add that or is there a spot I can do it?

**Comment by c0lp4nik** [comment]
Apologies everybody hates RTFM OR RYFG OR ID10T errors. Problem here behind keyboard for not seeing updated config on landing page! Will try it!

**Comment by c0lp4nik** [comment]
Also stumbled upon these switches which may be useful in the future:

/smart-scaling /size:1280x900 (example)

And 

/scale-desktop:200

And thanks for adding the UHD piece. Appreciate it.
