### ISSUE TITLE
Cannot make winapps work

### ISSUE THREAD

**Issue by knminhaz** [Fmstrat/winapps#345]
Hello,

I followed the tutorial on how to install windows till the "Begin install" stage. After the windows logo shows, the BSOD blue screen comes up and the it restarts and says no bootable device.

Please guide me.

System: Arch
CPU: AMD

**Comment by knminhaz** [comment]
Found the issue. Resolved

**Comment by ArnoldasMk** [comment]
Can you link it ? Having the same issue.

**Comment by ArnoldasMk** [comment]
Can you link it ? Having the same issue.
