### ISSUE TITLE
Can run games?

### ISSUE THREAD

**Issue by yezz123** [Fmstrat/winapps#35]
As example run some basic games like pubg or fortnite with using this?
And if yes is that based on https://www.winehq.org/

**Comment by Tiebe** [comment]
It's definitely not using Wine, since you're running a virtual machine on your computer, and you're just connecting using Remote Desktop. It can't run games right now, since it has pretty bad latency for games. I believe they are looking into fixing that though, so keep checking #33 and #28

**Comment by 6rube** [comment]
It is a virtual machine I don't think it can use the graphics card. U could try to do a **GPU pass-through** but it is really hard to configure and might not be that stable. And no it is not based on wine. If you want to play games on your linux computer you should search up proton and dxvk for linux.

**Comment by SushyDev** [comment]
it would be cool if we could do GPU passthrough on this, I don't think it should be that hard especially when a more talented person than me could write a guide for it

**Comment by Fmstrat** [comment]
I have a GPU passthrough script for qemu that works with this setup. However, that would only allow two things:
1) Run games on another monitor hooked to the second GPU
2) Use the GPU for background rendering in apps like Fusion360

It would not pass the GPU acceleration through the RDP session. Though I am investigating RemoteFX

**Comment by SushyDev** [comment]
> I have a GPU passthrough script for qemu that works with this setup. However, that would only allow two things:
> 
> 1. Run games on another monitor hooked to the second GPU
> 2. Use the GPU for background rendering in apps like Fusion360
> 
> It would not pass the GPU acceleration through the RDP session. Though I am investigating RemoteFX

Check out looking glass, maybe you can implement something with that

**Comment by Fmstrat** [comment]
https://looking-glass.io/

I will, but I have a feeling this is full-display, and won't allow for app segregation.

**Comment by zeitue** [comment]
> I have a GPU passthrough script for qemu that works with this setup. However, that would only allow two things:
> 
> 1. Run games on another monitor hooked to the second GPU
> 2. Use the GPU for background rendering in apps like Fusion360
> 
> It would not pass the GPU acceleration through the RDP session. Though I am investigating RemoteFX

Can I get this script, I've been looking for something to do exactly those two things.
