### ISSUE TITLE
VM Installation Instructions 3 Years Outdated

### ISSUE THREAD

**Issue by IfGremlinThen** [Fmstrat/winapps#353]
The winapps/docs/KVM.md install guide is apparently 3 years outdated.

`virt-manager` does not use the same step-by-step process to install as the guide demonstrates.  It does not automatically install `qemu`, which does not recognize host virtualization out of the box, and the default Libvirt-LXC errors out without also installing `libvirt-daemon-driver-lxc`.

Attempting to install with Libvirt-LXC requests a path to a pre-existing OS root directory, which `virt-manager` says requires `virt-bootstrap` which is yet another program that needs to be built from source.

**Comment by freechelmi** [comment]
Thanks all for your contributions

Winapps dev now takes place here https://github.com/winapps-org/winapps

So we can close this issue for good
