### ISSUE TITLE
Can't start RDPWindows

### ISSUE THREAD

**Issue by KabesaKubo** [Fmstrat/winapps#37]
Hello, first of all I have no idea about linux, so I just copy and paste line by line every install instruction. When I start RDPWindows (me or the install.sh script), I get this error
`error: Failed to start domain RDPWindows
error: internal error: Process exited prior to exec: libvirt: QEMU Driver error : Unable to stat RDPWindows.qcow2: No such file or directory`

Running Ubuntu 20.10

Any thoughts?

**Comment by Tiebe** [comment]
You need to change the XML to go to your real path. Something like /home/user/winapps/kvm/RDPWindows.qcow2

**Comment by Fmstrat** [comment]
You could also create the KVM VM from scratch using `virt-manager`. That may be easier if you're new to it.

**Comment by Altffenser** [comment]
Or put the .qcow2 file on root folder.
`sudo cp Downloads/winapps/kvm/RDPWindows.qcow2 /`

**Comment by KabesaKubo** [comment]
Ok thank you all, I thought Windows was already installed on the virtual disk, I'll install it manually!
