### ISSUE TITLE
Command line parsing failed at 'app' value 'explorer.exe'

### ISSUE THREAD

**Issue by zany130** [Fmstrat/winapps#375]
followed https://github.com/Fmstrat/winapps#installation and https://github.com/Fmstrat/winapps/blob/main/docs/KVM.md
 and I get 

 ```
 [20:58:33:040] [715048:000ae928] [ERROR][com.freerdp.client.common.cmdline] - [freerdp_client_settings_parse_command_line_arguments_int]: Command line parsing failed at 'app' value 'explorer.exe' [-1002]
```

when I run `bin/winapps check `

and I specify the VM IP in `.config/winapps/winapps.conf `

when I comment out the IP  I get

```
RDPWindows is not running, run:
  virsh start RDPWindows
```
even though I have a VM named `RDPWindows` already running

log shows

```                                 ─╯
───────┬─────────────────────────────────────────────────────────────────────────────────────
       │ File: .local/share/winapps/winapps.log
───────┼─────────────────────────────────────────────────────────────────────────────────────
   1   │ [Fri Aug  2 09:31:01 PM EDT 2024-26275] START
   2   │ [Fri Aug  2 09:31:01 PM EDT 2024-26275] 1:check
   3   │ [Fri Aug  2 09:31:01 PM EDT 2024-26275] 2:
   4   │ [Fri Aug  2 09:31:01 PM EDT 2024-26275] @:check
   5   │ [Fri Aug  2 09:31:01 PM EDT 2024-26275] CHECK
   6   │ [Fri Aug  2 09:31:01 PM EDT 2024-26275] END
```

**Comment by zany130** [comment]
looks like its a fedora issue https://github.com/FreeRDP/FreeRDP/issues/10249

**Comment by JustPrem** [comment]
The fix for this is:

- When inside the winapps folder, run "sudo nano bin/winapps" to open the winapps file we're checking, scroll until you find the following three long lines (at the bottom of the file, image attached)
![image](https://github.com/user-attachments/assets/2106d270-a625-4e1b-a321-6d927c6f85f6)

the middle if statement line will have "/app:"explorer.exe" at the end, change it to "/app:program:"explorer.exe" and then CTRL+O -> Enter -> CTRL+X to save and exit.

And that's it, bin/winapps check should now work.

**Comment by SavvyRat** [comment]
> The fix for this is:
> 
>     * When inside the winapps folder, run "sudo nano bin/winapps" to open the winapps file we're checking, scroll until you find the following three long lines (at the bottom of the file, image attached)
>       ![image](https://private-user-images.githubusercontent.com/91987927/372521279-2106d270-a625-4e1b-a321-6d927c6f85f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MzAzMjEsIm5iZiI6MTcyODczMDAyMSwicGF0aCI6Ii85MTk4NzkyNy8zNzI1MjEyNzktMjEwNmQyNzAtYTYyNS00ZTFiLWEzMjEtNmQ5MjdjNmY4NWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDEwNDcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNjk4OTIzMmRkMmM0OTBiNDYwZmRhMWYzY2YxNTgzMzZjYTJhOTYzNDAwZTJlYjQ4NmMzZjdiMzA2ZDJlYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vecu6tDtYKJCF672ZCXn8gGFmds8cSV8knKvBvaXcfo)
> 
> 
> the middle if statement line will have "/app:"explorer.exe" at the end, change it to "/app:program:"explorer.exe" and then CTRL+O -> Enter -> CTRL+X to save and exit.
> 
> And that's it, bin/winapps check should now work.

That did it for me, thank you!
