### ISSUE TITLE
Follow the XDG Base Directory Specification

### ISSUE THREAD

**Issue by Janfel** [Fmstrat/winapps#376]
Hi, I’ve noticed that you use hard-coded paths to `$HOME/.local/share/winapps` in a lot of places. Can you maybe change those to `${XDG_DATA_HOME:-"$HOME/.local/share"}/winapps`, `${XDG_CONFIG_HOME:-"$HOME/.config"}/winapps` etc. to conform to the XDG Base Directory Specification? See https://specifications.freedesktop.org/basedir-spec/latest/.

**Comment by alosslessdev** [comment]
Winapps development has moved to https://github.com/winapps-org/winapps

**Comment by Janfel** [comment]
Thanks, I’ve moved this issue to https://github.com/winapps-org/winapps/issues/236.
