### ISSUE TITLE
Shows an error when virsh define kvm/RDPWindows.xml

### ISSUE THREAD

**Issue by ginhiki** [Fmstrat/winapps#38]
when i enter the command virsh define kvm/RDPWindows.xml

It gives an error like this
error: Failed to define domain from kvm/RDPWindows.xml
error: An error occurred, but the cause is unknown
I am kind of a noob and just followed the steps in option 1 directly, Running archlinux i3 with linux-ck kernel 5.9.7-1-ck-skylake

**Comment by Anunayj** [comment]
Duplicate of #13
