### ISSUE TITLE
Linux Newbie here. Need help.

### ISSUE THREAD

**Issue by FocusBlast** [Fmstrat/winapps#40]
How and where do I make the config file?

**Comment by Fmstrat** [comment]
I'm not sure what you mean, do you mean the `~/.config/winapps/winapps.conf`?

**Comment by FocusBlast** [comment]
The first step in the tutorial is "create the winapps.conf file" right? How do I create one?

**Comment by Fmstrat** [comment]
```
mkdir -p ~/.config/winapps
nano ~/.config/winapps/winapps.conf
```

**Comment by FocusBlast** [comment]
Thanks!
