### ISSUE TITLE
guest CPU doesn't match specification

### ISSUE THREAD

**Issue by dcowan-london** [Fmstrat/winapps#42]
On starting the KVM machine, I get a pop up with the following error:
`Error starting domain: operation failed: guest CPU doesn't match specification: missing features: ss,fma,movbe,aes,f16c,rdrand,fsgsbase,bmi1,avx2,smep,bmi2,erms,invpcid,pdpe1gb,abm`

When I click 'Details', I get the following:
```
Error starting domain: operation failed: guest CPU doesn't match specification: missing features: ss,fma,movbe,aes,f16c,rdrand,fsgsbase,bmi1,avx2,smep,bmi2,erms,invpcid,pdpe1gb,abm

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 75, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 111, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 66, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1279, in startup
    self._backend.create()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 1234, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirt.libvirtError: operation failed: guest CPU doesn't match specification: missing features: ss,fma,movbe,aes,f16c,rdrand,fsgsbase,bmi1,avx2,smep,bmi2,erms,invpcid,pdpe1gb,abm
```

Thank you in advance!

**Comment by dasper** [comment]
The default XML file presumes a current Intel CPU which does not work if you are running an AMD CPU or an older Intel architecture (like a Sandy Bridge or Nehalem). You can most likely fix this by opening up your virtual machine manager, right click on the vm and select open, then click show virtual hardware details, and for CPU, choose `Hypervisor Default`
![Screenshot from 2020-11-11 09-27-49](https://user-images.githubusercontent.com/976723/98837966-d8c01900-2400-11eb-953a-a844735a3c62.png)

**Comment by dcowan-london** [comment]
Thank you! This worked.
