### ISSUE TITLE
The RDP connection failed to connect or run.

### ISSUE THREAD

**Issue by Phosphorus-M** [Fmstrat/winapps#43]
I follow all instructions but you lost me in the step:
`Merge kvm/RDPApps.reg into the registry to enable RDP Applications`
I don't know how to send the file inside the VM.
But I change the register with `regedit.exe`. I change the 0 to 1.
Now I made all steps but when I try to run the install script this happen:
![image](https://user-images.githubusercontent.com/19656993/98834128-9ce77c80-241d-11eb-9a17-74d13e6bdcc7.png)
I don't know what made bad, I don't have installed any of the programs in the list, but I made my customs files with the programs that I installed.
For example, I create a folder inside of apps named "opera-gx", inside I put the icon and the info file, with the route where I installed Opera GX.
But it's not mapped. I don't know if the problem it's my custom file or the error it's because I follow bad the steps.

**Comment by markiarpad** [comment]
Hi,

I have the same problem: I installed the KVM, I have RDPWindows VM (win10 enterprise, RDP on, virbr0 IP: 192.168.122.1.
The winapps.conf (the user and pwd was set correctly):

RDP_USER="something"
RDP_PASS="anypassword"
#RDP_DOMAIN="MYDOMAIN"
RDP_IP="192.168.122.1"
#RDP_SCALE=100
#MULTIMON="true"
DEBUG="true"

virsh list output:
Id   Name         State
----------------------------
 2    RDPWindows   running

If I run the install.sh (not as root): 
Installing...
  Checking for installed apps in RDP machine... Finished.
The RDP connection failed to connect or run.

The log file:
[2020. nov. 11., szerda, 17:59:01 CET-28306] START
[2020. nov. 11., szerda, 17:59:01 CET-28306] LAST_RAN:1605113413
[2020. nov. 11., szerda, 17:59:01 CET-28306] THIS_RUN:1605113942
[2020. nov. 11., szerda, 17:59:01 CET-28306] 1:install
[2020. nov. 11., szerda, 17:59:01 CET-28306] 2:
[2020. nov. 11., szerda, 17:59:01 CET-28306] @:install
[2020. nov. 11., szerda, 17:59:01 CET-28306] END

Unfortunately, I have no any idea, what is the problem...
Thank you for your help!

**Comment by Anunayj** [comment]
I had something similar happen, I just used freerdp to manually connect to the server and accepted the server certificate like in #41

**Comment by brendanperry** [comment]
I have this issue as well. I'll comment back if I find anything.

**Comment by tcg96** [comment]
I am also having this issue. Trying to connect from an Ubuntu 20.04 computer to a Windows 7 VirtualBox machine with bridged networking in another computer in the same LAN.

Connecting manually with xfreerdp (command `xfreerdp /v:[IP address]`) works fine, but when running `install.sh` I have the same error and log as above, even though the file `~/.config/winapps/winapps.conf` is configured correctly. In the Windows machine I set the computer name to RDPWindows and I ran the `.reg` file.

**Comment by Fmstrat** [comment]
Can you guys add `set -x` near the beginning of `install.sh` to see where it's actually erroring?

**Comment by Phosphorus-M** [comment]
@Fmstrat nop, I added the `set` at the beginning of `install.sh`
![image](https://user-images.githubusercontent.com/19656993/98969919-1c448100-24ee-11eb-88bd-431de76eff5e.png)
But I have the same output.
![image](https://user-images.githubusercontent.com/19656993/98969992-32524180-24ee-11eb-8867-7a06418945a4.png)
And the log doesn't add anything.
![image](https://user-images.githubusercontent.com/19656993/98970056-46963e80-24ee-11eb-8f08-da4ef289b272.png)

**Comment by tcg96** [comment]
I switched from a Windows 7 VirtualBox machine to a Windows 10 VMware Player machine and now it works for me. However before I could get it to work I had to run this command to connect manually: `xfreerdp /d: /u:USER /p:PASSWORD /v:IPADDRESS` (replacing the things in uppercase with the correct values, of course), then disconnect and finally run `install.sh`.

**Comment by markiarpad** [comment]
@Phosphorus-M : use set -x and not set +x (it does not change anything jut write out some information).

@tcg96 : when I use xfreerdp /d: /u:myusername /p:mypassword /v:192.168.122.1 I got the following:

[18:17:56:764] [31876:31877] [INFO][com.freerdp.core] - freerdp_connect:freerdp_set_last_error_ex resetting error state
[18:17:56:817] [31876:31877] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[18:17:56:860] [31876:31877] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[18:17:56:865] [31876:31877] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[18:17:56:183] [31876:31877] [INFO][com.freerdp.primitives] - primitives autodetect, using optimized
[18:17:57:740] [31876:31877] [INFO][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
[18:17:57:740] [31876:31877] [INFO][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
[18:17:57:741] [31876:31877] [ERROR][com.freerdp.core.transport] - BIO_should_retry returned a system error 32: Broken channel (the last 2 words were hungarian, so I translated it)
[18:17:57:741] [31876:31877] [ERROR][com.freerdp.core] - transport_write:freerdp_set_last_error_ex ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D]
[18:17:58:903] [31876:31877] [INFO][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
[18:17:58:903] [31876:31877] [INFO][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
[18:17:58:903] [31876:31877] [ERROR][com.freerdp.core.transport] - BIO_should_retry returned a system error 32: Törött adatcsatorna
[18:17:58:903] [31876:31877] [ERROR][com.freerdp.core] - transport_write:freerdp_set_last_error_ex ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D]
[18:17:58:904] [31876:31877] [ERROR][com.freerdp.core] - freerdp_post_connect failed

virsh list --all output:

Id   Name         State
----------------------------
 2    RDPWindows   running

My virbr0 IP: 192.168.122.1

@Fmstrat : the first part of the install.sh output:
++ cd .
++ pwd
+ DIR=/home/marki/Letöltések/winapps/winapps
+ . /home/marki/Letöltések/winapps/winapps/bin/winapps install
++ '[' '!' -f /home/marki/.config/winapps/winapps.conf ']'
++++ readlink -f ./install.sh
+++ dirname /home/marki/Letöltések/winapps/winapps/install.sh
++ DIR=/home/marki/Letöltések/winapps/winapps
+++ date
++ RUN='2020. nov. 12., csütörtök, 18:12:29 CET-6278'
++ '[' '!' -d /home/marki/.local/share/winapps ']'
++ RDP_SCALE=100
++ '[' -f /home/marki/.config/winapps/winapps.conf ']'
++ . /home/marki/.config/winapps/winapps.conf
+++ RDP_USER=myusername
+++ RDP_PASS=mypasswd
+++ RDP_IP=192.168.122.1
+++ DEBUG=true
++ dprint START
++ '[' true = true ']'
++ echo '[2020. nov. 12., csütörtök, 18:12:29 CET-6278] START'
++ '[' -f /home/marki/.local/share/winapps/run ']'
+++ stat -t -c %Y /home/marki/.local/share/winapps/run
++ LAST_RAN=1605162861
++ dprint LAST_RAN:1605162861
++ '[' true = true ']'
++ echo '[2020. nov. 12., csütörtök, 18:12:29 CET-6278] LAST_RAN:1605162861'
++ touch /home/marki/.local/share/winapps/run
+++ stat -t -c %Y /home/marki/.local/share/winapps/run
++ THIS_RUN=1605201149
++ dprint THIS_RUN:1605201149
++ '[' true = true ']'
++ echo '[2020. nov. 12., csütörtök, 18:12:29 CET-6278] THIS_RUN:1605201149'
++ ((  1605201149 - 1605162861 < 2  ))
+++ which xfreerdp
++ '[' -z /usr/bin/xfreerdp ']'
++ '[' -z 192.168.122.1 ']'
++ dprint 1:install
++ '[' true = true ']'
++ echo '[2020. nov. 12., csütörtök, 18:12:29 CET-6278] 1:install'
++ dprint 2:
++ '[' true = true ']'
++ echo '[2020. nov. 12., csütörtök, 18:12:29 CET-6278] 2:'
++ dprint @:install
++ '[' true = true ']'
++ echo '[2020. nov. 12., csütörtök, 18:12:29 CET-6278] @:install'
++ MULTI_FLAG=span
++ '[' '' = true ']'
++ '[' install = windows ']'
++ '[' install '!=' install ']'
++ dprint END
++ '[' true = true ']'

Ido not copy the middle part related to the checking the installed apps
the last part of the install.sh output:

+ LAST_RAN=1605201151
+ sleep 6
+ sleep 6
+ xfreerdp /u:myusernamei /p:mypasswd /v:192.168.122.1 +auto-reconnect +home-drive -wallpaper /span /wm-class:RDPInstaller '/app:C:\Windows\System32\cmd.exe' /app-icon:/home/marki/Letöltések/winapps/winapps/../icons/windows.svg '/app-cmd:/C \\tsclient\home\.local\share\winapps\installed.bat'
+ COUNT=0
++ stat -t -c %Y /home/marki/.local/share/winapps/installed
+ THIS_RUN=1605201151
+ ((  1605201151 - 1605201151 < 5  ))
+ sleep 5
++ stat -t -c %Y /home/marki/.local/share/winapps/installed
+ THIS_RUN=1605201151
+ COUNT=1
+ ((  COUNT == 5  ))
+ ((  1605201151 - 1605201151 < 5  ))
+ sleep 5
++ stat -t -c %Y /home/marki/.local/share/winapps/installed
+ THIS_RUN=1605201151
+ COUNT=2
+ ((  COUNT == 5  ))
+ ((  1605201151 - 1605201151 < 5  ))
+ sleep 5
++ stat -t -c %Y /home/marki/.local/share/winapps/installed
+ THIS_RUN=1605201151
+ COUNT=3
+ ((  COUNT == 5  ))
+ ((  1605201151 - 1605201151 < 5  ))
+ sleep 5
++ stat -t -c %Y /home/marki/.local/share/winapps/installed
+ THIS_RUN=1605201151
+ COUNT=4
+ ((  COUNT == 5  ))
+ ((  1605201151 - 1605201151 < 5  ))
+ sleep 5
++ stat -t -c %Y /home/marki/.local/share/winapps/installed
+ THIS_RUN=1605201151
+ COUNT=5
+ ((  COUNT == 5  ))
+ echo ' Finished.'
 Finished.
+ echo 'The RDP connection failed to connect or run.'
The RDP connection failed to connect or run.
+ exit

Thank you.

**Comment by Phosphorus-M** [comment]
@markiarpad Thank you
I share my log
https://gist.github.com/Phosphorus-M/763bc025f2e35bc7f495be25846cc41b

**Comment by Fmstrat** [comment]
Given the response from @tcg96 I wonder if you are all running into this: https://github.com/Fmstrat/winapps/issues/41

**Comment by waldaldo** [comment]
I do not know if it is the same problem but I could not connect to the vm if it was not with sudo, until I did the following

Try copying this file to your local config directory if you don't have it

`cp /etc/libvirt/libvirt.conf ~/.config/libvirt/libvirt.conf`

then uncomment this line

`uri_default = "qemu:///system"`

and all worked for me. I'm in Manjaro btw..

**Comment by mfeme2019** [comment]
Hi! I'm stuck at step 5 .. when I run "bin/winapps check" I get this error:

./bin/winapps: line 79: /home/martin/winapps/bin/../apps/check/info: File or directory does not exist

I'm also not sure if I'm executing the "Merge kvm / RDPApps.reg into the registry to enable RDP Applications" step correctly. Just use regedit and change the value to 1?
If I continue to the next step, then:

Installing...
  Checking for installed apps in RDP machine... Finished.
The RDP connection failed to connect or run.

What can be the problem with the RDP connection?

**Comment by waldaldo** [comment]
> I'm also not sure if I'm executing the "Merge kvm / RDPApps.reg into the registry to enable RDP Applications" step correctly. Just use regedit and change the value to 1?

Easy way: Log into the vm and download the reg file an apply.

**Comment by e-belair** [comment]
I'm getting the same problem, I tried the @waldaldo solution, but did not work
I disabled the windows firewall and manually set the IP address in the winapps conf file
Here is the logs:
[log.txt](https://github.com/Fmstrat/winapps/files/5535943/log.txt)

**Comment by Fmstrat** [comment]
@e-belair I think your quotes are in the wrong place. It should be `/app:'command'`

**Comment by e-belair** [comment]
> @e-belair I think your quotes are in the wrong place. It should be `/app:'command'`

I just copied/pasted the line from the log file. Anyway, `xfreerdp /d: /u:manu /p:manu /v:192.168.122.77 +auto-reconnect +home-drive -wallpaper /span /wm-class:RDPInstaller /app:'C:\Windows\System32\cmd.exe'` give me the same result
Also `xfreerdp /d: /u:manu /p:manu /v:192.168.122.77 +auto-reconnect +home-drive -wallpaper /span /wm-class:RDPInstaller /app:'||calc'` give the same error.
I also tried to add this reg i found on a [thread](https://superuser.com/questions/955446/remote-desktop-how-can-i-enable-remoteapp-serving-in-windows-10):
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services] "fAllowUnlistedRemotePrograms"=dword:00000001
```
Unfortunetly not working :disappointed:

**Comment by Fmstrat** [comment]
What about:
```
xfreerdp /d: /u:manu /p:manu /v:192.168.122.77 /app:"cmd.exe"
```
If that bombs, you'll probably need a ticket with FreeRDP.

**Comment by e-belair** [comment]
I just discovered that I was using a very old windows 10 pro. After installed the latest windows updates, I could connect
But now on ./install.sh, I'm getting a full black screen lol. So I'll investigate this new problem ...

**Comment by Phosphorus-M** [comment]
Omg in my case I did what @waldaldo and @e-belair, I shut down the virtual machine and restarted, and now the `install.sh` works.
Thank you very much.
![image](https://user-images.githubusercontent.com/19656993/99125800-94d93980-25e3-11eb-8ea0-d4b3e40b160c.png)

**Comment by bphd** [comment]
> @Phosphorus-M : use set -x and not set +x (it does not change anything jut write out some information).
> 
> @tcg96 : when I use xfreerdp /d: /u:myusername /p:mypassword /v:192.168.122.1 I got the following:
> 
> [18:17:56:764] [31876:31877] [INFO][com.freerdp.core] - freerdp_connect:freerdp_set_last_error_ex resetting error state [18:17:56:817] [31876:31877] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr [18:17:56:860] [31876:31877] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd [18:17:56:865] [31876:31877] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr [18:17:56:183] [31876:31877] [INFO][com.freerdp.primitives] - primitives autodetect, using optimized [18:17:57:740] [31876:31877] [INFO][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state [18:17:57:740] [31876:31877] [INFO][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state [18:17:57:741] [31876:31877] [ERROR][com.freerdp.core.transport] - BIO_should_retry returned a system error 32: Broken channel (the last 2 words were hungarian, so I translated it) [18:17:57:741] [31876:31877] [ERROR][com.freerdp.core] - transport_write:freerdp_set_last_error_ex ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D] [18:17:58:903] [31876:31877] [INFO][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state [18:17:58:903] [31876:31877] [INFO][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state [18:17:58:903] [31876:31877] [ERROR][com.freerdp.core.transport] - BIO_should_retry returned a system error 32: Törött adatcsatorna [18:17:58:903] [31876:31877] [ERROR][com.freerdp.core] - transport_write:freerdp_set_last_error_ex ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D] [18:17:58:904] [31876:31877] [ERROR][com.freerdp.core] - freerdp_post_connect failed
> 
> virsh list --all output:
> ## Id Name State
> 
> 2 RDPWindows running
> 
> My virbr0 IP: 192.168.122.1
> 
> @Fmstrat : the first part of the install.sh output: ++ cd . ++ pwd
> 
>     * DIR=/home/marki/Letöltések/winapps/winapps
> 
>     * . /home/marki/Letöltések/winapps/winapps/bin/winapps install
>       ++ '[' '!' -f /home/marki/.config/winapps/winapps.conf ']'
>       ++++ readlink -f ./install.sh
>       +++ dirname /home/marki/Letöltések/winapps/winapps/install.sh
>       ++ DIR=/home/marki/Letöltések/winapps/winapps
>       +++ date
>       ++ RUN='2020. nov. 12., csütörtök, 18:12:29 CET-6278'
>       ++ '[' '!' -d /home/marki/.local/share/winapps ']'
>       ++ RDP_SCALE=100
>       ++ '[' -f /home/marki/.config/winapps/winapps.conf ']'
>       ++ . /home/marki/.config/winapps/winapps.conf
>       +++ RDP_USER=myusername
>       +++ RDP_PASS=mypasswd
>       +++ RDP_IP=192.168.122.1
>       +++ DEBUG=true
>       ++ dprint START
>       ++ '[' true = true ']'
>       ++ echo '[2020. nov. 12., csütörtök, 18:12:29 CET-6278] START'
>       ++ '[' -f /home/marki/.local/share/winapps/run ']'
>       +++ stat -t -c %Y /home/marki/.local/share/winapps/run
>       ++ LAST_RAN=1605162861
>       ++ dprint LAST_RAN:1605162861
>       ++ '[' true = true ']'
>       ++ echo '[2020. nov. 12., csütörtök, 18:12:29 CET-6278] LAST_RAN:1605162861'
>       ++ touch /home/marki/.local/share/winapps/run
>       +++ stat -t -c %Y /home/marki/.local/share/winapps/run
>       ++ THIS_RUN=1605201149
>       ++ dprint THIS_RUN:1605201149
>       ++ '[' true = true ']'
>       ++ echo '[2020. nov. 12., csütörtök, 18:12:29 CET-6278] THIS_RUN:1605201149'
>       ++ ((  1605201149 - 1605162861 < 2  ))
>       +++ which xfreerdp
>       ++ '[' -z /usr/bin/xfreerdp ']'
>       ++ '[' -z 192.168.122.1 ']'
>       ++ dprint 1:install
>       ++ '[' true = true ']'
>       ++ echo '[2020. nov. 12., csütörtök, 18:12:29 CET-6278] 1:install'
>       ++ dprint 2:
>       ++ '[' true = true ']'
>       ++ echo '[2020. nov. 12., csütörtök, 18:12:29 CET-6278] 2:'
>       ++ dprint @:install
>       ++ '[' true = true ']'
>       ++ echo '[2020. nov. 12., csütörtök, 18:12:29 CET-6278] @:install'
>       ++ MULTI_FLAG=span
>       ++ '[' '' = true ']'
>       ++ '[' install = windows ']'
>       ++ '[' install '!=' install ']'
>       ++ dprint END
>       ++ '[' true = true ']'
> 
> 
> Ido not copy the middle part related to the checking the installed apps the last part of the install.sh output:
> 
>     * LAST_RAN=1605201151
> 
>     * sleep 6
> 
>     * sleep 6
> 
>     * xfreerdp /u:myusernamei /p:mypasswd /v:192.168.122.1 +auto-reconnect +home-drive -wallpaper /span /wm-class:RDPInstaller '/app:C:\Windows\System32\cmd.exe' /app-icon:/home/marki/Letöltések/winapps/winapps/../icons/windows.svg '/app-cmd:/C \tsclient\home.local\share\winapps\installed.bat'
> 
>     * COUNT=0
>       ++ stat -t -c %Y /home/marki/.local/share/winapps/installed
> 
>     * THIS_RUN=1605201151
> 
>     * ((  1605201151 - 1605201151 < 5  ))
> 
>     * sleep 5
>       ++ stat -t -c %Y /home/marki/.local/share/winapps/installed
> 
>     * THIS_RUN=1605201151
> 
>     * COUNT=1
> 
>     * ((  COUNT == 5  ))
> 
>     * ((  1605201151 - 1605201151 < 5  ))
> 
>     * sleep 5
>       ++ stat -t -c %Y /home/marki/.local/share/winapps/installed
> 
>     * THIS_RUN=1605201151
> 
>     * COUNT=2
> 
>     * ((  COUNT == 5  ))
> 
>     * ((  1605201151 - 1605201151 < 5  ))
> 
>     * sleep 5
>       ++ stat -t -c %Y /home/marki/.local/share/winapps/installed
> 
>     * THIS_RUN=1605201151
> 
>     * COUNT=3
> 
>     * ((  COUNT == 5  ))
> 
>     * ((  1605201151 - 1605201151 < 5  ))
> 
>     * sleep 5
>       ++ stat -t -c %Y /home/marki/.local/share/winapps/installed
> 
>     * THIS_RUN=1605201151
> 
>     * COUNT=4
> 
>     * ((  COUNT == 5  ))
> 
>     * ((  1605201151 - 1605201151 < 5  ))
> 
>     * sleep 5
>       ++ stat -t -c %Y /home/marki/.local/share/winapps/installed
> 
>     * THIS_RUN=1605201151
> 
>     * COUNT=5
> 
>     * ((  COUNT == 5  ))
> 
>     * echo ' Finished.'
>       Finished.
> 
>     * echo 'The RDP connection failed to connect or run.'
>       The RDP connection failed to connect or run.
> 
>     * exit
> 
> 
> Thank you.

Any update on the transport failed?
