### ISSUE TITLE
GNOME Crash on POP OS 20.10

### ISSUE THREAD

**Issue by pahofmann** [Fmstrat/winapps#45]
I've just installed it (with a pre-existing vm), installation went fine. 

But when starting any office app my gnome desktop glitches (windows get moved around and black desktop background) and then the gnome session crashes and I'm forced to log out.  

Same behavjour when all gnome-shell-plugins are disabled, anyone else ran into an issue like this?

**Comment by Tiebe** [comment]
Same here on Kali Linux. I've went to just using the Windows shortcut and opening applications from there.

**Comment by leocelente** [comment]
I had the same issue. In my case it stopped crashing when I switched to the built-in monitor only. After that I tried switching to Integrated Graphics and now it works with both monitors (so far). I noted some strange behavior (but no crash) while running on Wayland

**Comment by leocelente** [comment]
Well, I was just switching back to Hybrid Graphics to run with the DEBUG config and now it all works fine. My guess is that I ran the install.sh in Integrated Graphics and that somehow made it always render in the intel gpu (??). But any guess is as good as mine

**Comment by pahofmann** [comment]
I tried on integrated display only as well with the same result.  
I run in integrated graphics only mode most of the time, as I'm docked and all my USB-C ports are wired to the integrated Graphics not the Nvidia unfortunately.

**Comment by Danhyal** [comment]
> Well, I was just switching back to Hybrid Graphics to run with the DEBUG config and now it all works fine. My guess is that I ran the install.sh in Integrated Graphics and that somehow made it always render in the intel gpu (??). But any guess is as good as mine

idk why but that worked for me aswell... so weird.

**Comment by pahofmann** [comment]
Tried it with and without MULTIMON (aswell as with/without external displays connected), didn't make a difference unfortunately.

**Comment by Fmstrat** [comment]
Does using `xfreerdp` independently cause the same issue? For instance, try:
```
. ~/.config/winapps/winapps.conf
set -x
xfreerdp /d:"${RDP_DOMAIN}" /u:"${RDP_USER}" /p:"${RDP_PASS}" /v:${RDP_IP} +auto-reconnect +home-drive -wallpaper /scale:${RDP_SCALE} /dynamic-resolution /${MULTI_FLAG} /app:"cmd.exe"
```
And paste the output here.

**Comment by pahofmann** [comment]
The same happens with the command you posted. I redirected the output to a log, here is the [output on pastebin](https://pastebin.com/Nd7aFh2t).

Using the `windows` command works fine though.

**Comment by Fmstrat** [comment]
What do you get from `xfreerdp /version`?

**Comment by pahofmann** [comment]
`This is FreeRDP version 2.2.0 (2.2.0)`

**Comment by Fmstrat** [comment]
I can only imagine this is FreeRDP issue, vs a WinApps issue, since the base `/app` command is causing the issue.

**Comment by pahofmann** [comment]
Are you running the same FreeRDP version?

**Comment by pahofmann** [comment]
After the latest POP OS updates from today, the command above launches the CMD just fine, no crashes.  

It still glitches wenn I use the desktop entry though, even with multimon and scale set in the config.
When I launch it again via the command, all programs are displayed correctly though.

Is there a difference in the options between the desktop entry with MULTIMON and SCALE 100 and
`xfreerdp /d:"${RDP_DOMAIN}" /u:"${RDP_USER}" /p:"${RDP_PASS}" /v:${RDP_IP} +auto-reconnect +home-drive -wallpaper /scale:100 /dynamic-resolution /span /app:"cmd.exe"`?

**Comment by Fmstrat** [comment]
@pahofmann Turning `MULTIMON` off might solve that.

**Comment by pahofmann** [comment]
Thanks, that seems to have done it!

**Comment by Tiebe** [comment]
Still happening for me, with or without ```MULTIMON```
