### ISSUE TITLE
The windows vm can't start

### ISSUE THREAD

**Issue by anganevagg** [Fmstrat/winapps#47]
error: Failed to start domain RDPWindows
error: internal error: Process exited prior to exec: libvirt: QEMU Driver error : Unable to stat RDPWindows.qcow2: No existe el archivo o el directorio

**Comment by thefoo547** [comment]
I have the same error, followed all steps as shown in Option 1.

**Comment by Tiebe** [comment]
Already gave an answer to this exact problem at #37
