### ISSUE TITLE
Please keep everything in HOME

### ISSUE THREAD

**Issue by jjgalvez** [Fmstrat/winapps#49]
First Thank you for a fantastic and very cool app!

A couple of thoughts, 1) there should be the option to install everything in home rather than having the executables and .desktop files installed centrally. I edited install to point to ~/.local/bin and ~/.local/share/applications. 2) windows hates to be just killed so please consider adding a bat file to shutdown /s /f /t 0  to shutdown windows easier. I also added a try program to start and close the VM (I'm suing virtualbox). 

Again great program and thanks.

**Comment by Fmstrat** [comment]
Glad you are enjoying it!

1) Dup: https://github.com/Fmstrat/winapps/issues/27
2) KVM handles shutdowns automatically via libvirtd. Existing an RDP application or instance doesn't shutdown
2.5) For KVM users I'll be adding a pause functionality: https://github.com/Fmstrat/winapps/issues/4

**Comment by jjgalvez** [comment]
Excellent, didn't know that KVM did that, I will have to give that a try.
