### ISSUE TITLE
Removal of apps from host?

### ISSUE THREAD

**Issue by jackforfaltu** [Fmstrat/winapps#50]
How can we remove unwanted apps from the host? Do we just remove the .desktop file from /usr/share/applications, is there another way (this way seems unclean and I'm afraid it might leave some files on the system which will bother later on).

**Comment by connlim** [comment]
[The install script files only puts app-specific files in `/usr/local/bin` and `/usr/share/applications`. ](https://github.com/Fmstrat/winapps/blob/main/install.sh#L56-L60)Deleting any unwanted apps from those 2 directories is enough.

**Comment by Fmstrat** [comment]
I will be doing this including:
- Detection of switch of system mode to user mode and remove shortcuts
- Detection of switch of user mode to system mode and remove shortcuts
- Remove all shortcuts with uninstall

As @connlim mentions, deleting the files is enough. The below should do it.

```bash
rm $(grep -l winapps /usr/share/applications/*)
rm $(grep -l winapps /usr/local/bin/*)
```

**Comment by jackforfaltu** [comment]
Ok thanks @connlim @Fmstrat 
Should I close or leave open for the enhancement tag to be completed?

**Comment by Fmstrat** [comment]
@jackforfaltu I'm going to close this out, because of this (now in the `README`):

## Installer usage
The following commands can be used to manage your application configurations:
``` bash
./installer.sh --user                # Configure applications for the current user
./installer.sh --system              # Configure applications for the entire system
./installer.sh --user --uninstall    # Remove all configured applications for the current user
./installer.sh --system --uninstall  # Remove all configured applications for the entire system
```
