### ISSUE TITLE
Can not create KVM Machine on openSUSE Leap 15.2

### ISSUE THREAD

**Issue by Alex-Dall** [Fmstrat/winapps#52]
Hello,

I tried to set the software up like it is discribed in the Readme file. Everthing worked fine until the following command:
`virsh define kvm/RDPWindows.xml`

I get the following error:
`Fehler: Fehler beim Definieren einer Domain von kvm/RDPWindows.xml
Fehler: Cannot check QEMU binary /usr/bin/kvm-spice: No such file or directory`

The english translation for the first line:
`Error: Error while defining a domain from kvm/RDPWindows.xml`

What else I have to install or what should I change in the RDPWindows.xml file to get it work.

I use openSuse Leap 15.2 and have installed KVM with YaSt. My desktop enviroment is KDE Plasma.

Would be cool if you could help me.

**Comment by pauljalmeida** [comment]
Esta acontecendo exatamente comigo não consigo passar desse passo

**Comment by Tiebe** [comment]
Run `sudo cp /usr/bin/qemu-system-x86_64 /usr/bin/kvm-spice` and then try again

**Comment by Alex-Dall** [comment]
Thanks for your answers,
I have set up my virtual machine with the virtual machine manager which worked.
@Tiebe  I will try your answer on my Laptop and tell you if it had worked.
