### ISSUE TITLE
Windows resizing via remote RDP session?

### ISSUE THREAD

**Issue by 0raculo** [Fmstrat/winapps#53]
Hi

I'm using a remote RDP server where everything works great but i can't resize windows. Can maximize and restore, but can't drag from a corner for a specific size.
Lenovo X380, Ubuntu 20.04

Side note, it would be awesome to use a SSH gateway for RDP instead of relying on VPN! (as i do in remmina)

Thanks!

**Comment by Fmstrat** [comment]
Dup: https://github.com/Fmstrat/winapps/issues/2

I'm not sure what specific you would need for an SSH gateway beyond opening up an `ssh -L` and using `localhost` for the `RDP_IP`. If there is something specific, please open a ticket with the details. Thanks!

**Comment by 0raculo** [comment]
Hi.

The ticket was about window resizing, but I do regret adding something else besides what was actually needed.
Apologies for that.

Should I open a new issue for windows not being able to resize with mouse cursor?

**Comment by kolle86** [comment]
As a workaround you can resive the windows with keyboard. Just press ALT+SPACE, select Resize from menu and resize the window with arrow keys. Should work on most desktop environments
