### ISSUE TITLE
Add an "winapps" catagory for all the apps

### ISSUE THREAD

**Issue by gzzchh** [Fmstrat/winapps#57]
also create an catagory name winapps in GNOME/KDE.  
This can make all winapps in a seperate catagory   
Sometimes it will help users find apps quickly

Example, like this

![image](https://user-images.githubusercontent.com/17796830/99147454-02f12f80-26bc-11eb-8dc9-9c94eeda51f0.png)

![image](https://user-images.githubusercontent.com/17796830/99147471-24521b80-26bc-11eb-8ff8-d9188f11d12d.png)

**Comment by Fmstrat** [comment]
This is a great idea.

**Comment by Fmstrat** [comment]
Annnnd done. https://github.com/Fmstrat/winapps/commit/f48256bda5902b500c64ac18ea8997d619b91e44
