### ISSUE TITLE
Error connecting or running RDP on Arch

### ISSUE THREAD

**Issue by Altffenser** [Fmstrat/winapps#63]
I have been passed to the last installation step on Arch, specifically in Manjaro but I got stuck there. When I run the command `$ bin/winapps check`the VM works properly, the windows explorer is shown and I can navigate in it but when I run the command `$ ./installer.sh --user`then shown

```
Removing any old configurations...
grep: /home/alex/.local/share/applications/*: No such file or directory
grep: /home/alex/.local/bin/*: No such file or directory
grep: /usr/local/bin/*: No such file or directory
Installing...
  Checking for installed apps in RDP machine (this may take a while)... Finished.
The RDP connection failed to connect or run.
```
For installation, it need the VM powered off or on?
What aspects to consider?

**Comment by Fmstrat** [comment]
Does Manjaro not use the standard `.local` paths or `/usr/local/bin`?

Despite those errors, it should still be connecting to the RDP session. If you run `bin/winapps check` again, does it ask to accept a cert every time?

**Comment by Altffenser** [comment]
> Does Manjaro not use the standard `.local` paths or `/usr/local/bin`?
> 
> Despite those errors, it should still be connecting to the RDP session. If you run `bin/winapps check` again, does it ask to accept a cert every time?

I think that's the problem.
No, if I want to connect it just does so, it has never asked me to accept certificates or even login data again.

I should mention that something strange happens to me (for me), when it shows me the error and after a few minutes, it automatically opens a session and the CMD is shown executing some instructions, it happens so fast that I can't read, I don't understand.

**Comment by Fmstrat** [comment]
Hmm, so it's doing what it should, then. That is RDP running a batch script to check for installed applications. My guess is since `.local` doesn't exist, it's not working. Try:
```
mkdir -p ~/.local/winapps
```
And then give it another shot.

**Comment by Altffenser** [comment]
> Hmm, so it's doing what it should, then. That is RDP running a batch script to check for installed applications. My guess is since `.local` doesn't exist, it's not working. Try:
> 
> ```
> mkdir -p ~/.local/share/winapps
> ```
> 
> And then give it another shot.

There was a breakthrough but I did a plus things like 
copy all _winapps/app_ folder content to `/home/alex/.local/share/applications/`
copy _winapps/bin/ to `/home/alex/.local/bin/`and `/usr/local/bin/`

The result was:
```
[alex@altffenser winapps]$ ./installer.sh --user
Removing any old configurations...
Installing...
  Checking for installed apps in RDP machine (this may take a while)... Finished.
  Configuring Cmd...tee: /home/alex/.local/share/applications/cmd.desktop: Permission denied
tee: /home/alex/.local/bin/cmd: Permission denied
chmod: cannot access '/home/alex/.local/bin/cmd': No such file or directory
 Finished.
  Configuring Windows...tee: /home/alex/.local/share/applications/windows.desktop: Permission denied
tee: //home/alex/.local/bin/windows: Permission denied
chmod: cannot access '/home/alex/.local/bin/windows': No such file or directory
 Finished.
Installation complete.
```

**Comment by Altffenser** [comment]
Finally works properly! you can see my [screenshot](https://i.imgur.com/gmhlEnd.png) thank you.
