### ISSUE TITLE
The RDP connection failed to connect or run

### ISSUE THREAD

**Issue by Raju** [Fmstrat/winapps#64]
There are two Issue's which I'm facing.

1. Unable to accept certificates.
![image](https://user-images.githubusercontent.com/42042961/99190486-c2adb200-278c-11eb-80e5-b583609b0667.png)

2. After running the installer.sh file, it take few minutes like 3 to 4 minutes and then throws error message **_"The RDP connection failed to connect or run"_**
![image](https://user-images.githubusercontent.com/42042961/99190476-b9244a00-278c-11eb-8d21-ac98d00a4f96.png)

System details - Ubuntu with below shown details,
![image](https://user-images.githubusercontent.com/42042961/99190503-e1ac4400-278c-11eb-9b2a-13875b0df9aa.png)

VM Details.
![image](https://user-images.githubusercontent.com/42042961/99190612-7b73f100-278d-11eb-9b38-8570608e958f.png)

Need some help fixing these errors.

**Comment by Tiebe** [comment]
Run 
```
. ~/.config/winapps/winapps.conf
xfreerdp ${RDP_FLAGS} /d:"${RDP_DOMAIN}" /u:"${RDP_USER}" /p:"${RDP_PASS}" /v:${RDP_IP} /scale:${RDP_SCALE} /dynamic-resolution +auto-reconnect +home-drive /wm-class:"Microsoft Windows"
```
And accept the certificate

**Comment by Fmstrat** [comment]
@Tiebe He would have hit a certificate acceptance in the `check` stage, so he's all good there. The warning there is normal.

@Raju I see a login failure warning in the check stage. Are your username/password/domain right?

**Comment by Fmstrat** [comment]
@tiebe Btw, thanks for jumping in an helping, I see you answering a number of these, super awesome to have the support.

**Comment by marcussacana** [comment]
I had a problem with the to connect with the RDP, in my case I solved by installing the RDP Wrapper in the VM

**Comment by alexandrepalaoro** [comment]
Another solution that worked for me was changing the windows user account. 

I changed the name, gave it a password, and changed the config accordingly. Worked like a charm.

**Comment by Raju** [comment]
Thanks for the quick reply @Tiebe , was busy with festival time but I'm back now.

The issue was due to incorrect username/password, I think most of the users are setting up windows using an email and then they try to use the username provided by windows and maybe a custom pin/password but instead we have to use the original email and password which was used to setup windows.

This helped me when I was trying with different username/password such as the username for windows and pin/password and also with email/password.

So we can let others know about this who are facing similar issues with RDP connection failed to connect or run to actually use the email/password if they used it to setup windows instead windows username/pin or password @Fmstrat .

**Comment by Fmstrat** [comment]
Good call: https://github.com/Fmstrat/winapps/commit/bd57452a6a45d4a7f449d70bb26600f7f05905fe

**Comment by Raju** [comment]
Happy to helo
