### ISSUE TITLE
Error when trying to save Office-Document to rclone mounted folder

### ISSUE THREAD

**Issue by kolle86** [Fmstrat/winapps#69]
Hi guys,
i've mounted my Office365 OneDrive with rclone to /home/username/OneDrive.
Opening Office-Documents from there (e.g. a docx. File) with Word via Winapps works fine, but when i try to save it says "There here has been a network or file permission error. The network connection may be lost" and it states the tsclient path.
Saving to other folders in my home is no problem.

I've mounted with following command:
`rclone --vfs-cache-mode writes mount OneDrive: ~/OneDrive`
The owner of the folder is me and in nautilus i have full write access.

Is this a problem with tsclient ? Why cant it write to this folder?
Any help appriciated :-)

**Comment by Tiebe** [comment]
This is probably because rclone makes a mount, which means the files are only there when you want to use them. Since Windows doesn't support this when it's on the Linux mount, it will throw an error.

Think of it as trying to access a mount inside a mount. It doesn't work, since rclone is never notified that the files need to be accessible.

**Comment by Fmstrat** [comment]
As @Tiebe pointed out, `rclone` uses a FUSE style mount, not a file system mount like you would have on a drive. It is POSSIBLE you could find the right combination of an `overlayfs` filesystem merged into an empty home directory and containing the `rclone` mount, but I have no idea how well that would work. Very interesting use case and interested to hear if you find a way.

**Comment by kolle86** [comment]
@Fmstrat For now, i ended up manipulating the FILE, which is handed over to the windows-application.
~Row 100 in winapps bin:
`		if [[ "${2}" == *"/home/username/OneDrive/"* ]]; then
  			FILE=$(echo "${2}" | sed 's|'"${HOME}/OneDrive"'|\\C:\\Users\\winapps\\OneDriveFolderNameOnVM|;s|/|\\|g;s|\\|\\\\|g')
		else
			FILE=$(echo "${2}" | sed 's|'"${HOME}"'|\\\\tsclient\\home|;s|/|\\|g;s|\\|\\\\|g')
		fi`
This replaces the tsclient path with the "real" path of vm. Within VM there is also OneDrive client installed with "sync on demand". 
This way i can browse my OneDrive and create files within etc in Nautilus; when opening a file it launches the office application with vm's path to local onedrive => Saving the File works

**Comment by Fmstrat** [comment]
Glad you were able to get it working!
