### ISSUE TITLE
How to debug undiscovered applications?

### ISSUE THREAD

**Issue by fbartels** [Fmstrat/winapps#75]
Hi, 

I noticed that when rerunning the install script it sometimes does not discover all applications. In the following example it only found some of the installed Microsoft Office applications (using 2019 Pro Plus):

```
Removing any old configurations...
  Removing /home/fbartels/.local/share/applications/access-x86.desktop... Finished.
  Removing /home/fbartels/.local/share/applications/cmd.desktop... Finished.
  Removing /home/fbartels/.local/share/applications/excel-o365-x86.desktop... Finished.
  Removing /home/fbartels/.local/share/applications/explorer.desktop... Finished.
  Removing /home/fbartels/.local/share/applications/iexplorer.desktop... Finished.
  Removing /home/fbartels/.local/share/applications/onenote-o365-x86.desktop... Finished.
  Removing /home/fbartels/.local/share/applications/outlook-o365-x86.desktop... Finished.
  Removing /home/fbartels/.local/share/applications/powerpoint-o365-x86.desktop... Finished.
  Removing /home/fbartels/.local/share/applications/powershell.desktop... Finished.
  Removing /home/fbartels/.local/share/applications/publisher-o365-x86.desktop... Finished.
  Removing /home/fbartels/.local/share/applications/windows.desktop... Finished.
  Removing /home/fbartels/.local/share/applications/word-o365-x86.desktop... Finished.
  Removing /home/fbartels/.local/bin/access-x86... Finished.
  Removing /home/fbartels/.local/bin/cmd... Finished.
  Removing /home/fbartels/.local/bin/excel-o365-x86... Finished.
  Removing /home/fbartels/.local/bin/explorer... Finished.
  Removing /home/fbartels/.local/bin/iexplorer... Finished.
  Removing /home/fbartels/.local/bin/onenote-o365-x86... Finished.
  Removing /home/fbartels/.local/bin/outlook-o365-x86... Finished.
  Removing /home/fbartels/.local/bin/powerpoint-o365-x86... Finished.
  Removing /home/fbartels/.local/bin/powershell... Finished.
  Removing /home/fbartels/.local/bin/publisher-o365-x86... Finished.
  Removing /home/fbartels/.local/bin/windows... Finished.
  Removing /home/fbartels/.local/bin/word-o365-x86... Finished.
Installing...
  Checking for installed apps in RDP machine (this may take a while)... Finished.
  Configuring Access... Finished.
  Configuring Cmd... Finished.
  Configuring Excel... Finished.
  Configuring Explorer... Finished.
  Configuring Internet Explorer... Finished.
  Configuring OneNote... Finished.
  Configuring Windows... Finished.
Installation complete.
```

Is there a log to check?

**Comment by Fmstrat** [comment]
Hmm.. if you ran it again, does it find them? I'm wondering if it's simply that the delays are too short and the filesystem hasn't fully synced the list of apps.

**Comment by fbartels** [comment]
Yes, on the next execution the programs were found again. I have not yet seen a pattern, but I anyways wanted to look into the code that discovers the binaries.

**Comment by fbartels** [comment]
I looked into https://github.com/Fmstrat/winapps/blob/main/installer.sh#L26-L47 can you just confirm that I get the intention behind this function right.

1. create a file on the windows system with the paths to known applications. the batch script
2. put a stop marker into the same file
3. wait 15 seconds (why?)
4. start file with paths (runs in the background?)
5. wait another 15 seconds
6. check the last modified of file created by batch script
7. if last modified was less than 5 seconds ago wait another 15 seconds
8. repeat the last step at max five time.

A quick fix would be to work with atomic file operations. let the batch script write the discovered applications in installed.temp and once the batch script is through move it from `installed.temp` to `installed`. You then only need to check if the file `installed` exists.

**Comment by Fmstrat** [comment]
https://github.com/Fmstrat/winapps/commit/bd57452a6a45d4a7f449d70bb26600f7f05905fe

**Comment by Fmstrat** [comment]
@fbartels Yes, you understand correctly. Above commit takes your suggestion into account. Thanks!

**Comment by fbartels** [comment]
Thanks! Seems to work more reliably now. Its also nice that the windows command prompt stays open makes it easier to check what is actually going on.

**Comment by Fmstrat** [comment]
@fbartels The installer I just released is even better, plus it will check for apps that are installed but not configured in WinApps (so just about everything on your machine can optionally be set up)
