### ISSUE TITLE
Why ~/.winapps instead of ~/.config/winapps?

### ISSUE THREAD

**Issue by perrsona1234** [Fmstrat/winapps#8]
Title says it all. Seriously, why are people so passionate about clogging user's /home directory with configuration files?

Can this be changed or configured manually by the user?

Other than that, this project looks interesting, thanks for making this! :D

**Comment by Fmstrat** [comment]
Yes, this can be changed.

**Comment by Fmstrat** [comment]
https://github.com/Fmstrat/winapps/commit/f86d774fa1df0a8e6605f79aaf5f03dbc00d2950

**Comment by farmerbobathan** [comment]
While the directory is being changed, can it also support the [XDG base directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)? Just have it use $XDG_CONFIG_HOME/winapps if the variable is set otherwise use ~/.config/winapps.
