### ISSUE TITLE
Bug with GNOME, can't click top bar and dock (Pop OS 20.10)

### ISSUE THREAD

**Issue by screamingDanana** [Fmstrat/winapps#81]
Great work on this 👍 I managed to setup everything and everything is working fine. However, I encountered a problem where I can't click GNOME interfaces such as the top bar and dock when the RDP is running. The click basically pass through the UI to the background application. I had to press the Super key (Overview key) to be able to click on the top bar and docks. It's pretty annoying.

Any workaround on this?

**Comment by Fmstrat** [comment]
Hmm, I haven't encountered this except when using PowerPoint in presentation mode. What OS and flags are you using in your config?

**Comment by screamingDanana** [comment]
Everything is on default from my config. I only change the RDP_USER and RDP_PASS
```
RDP_USER="default"
RDP_PASS="default"
#RDP_DOMAIN="MYDOMAIN"
#RDP_IP="192.168.123.111"
#RDP_SCALE=100
#RDP_FLAGS=""
#MULTIMON="true"
#DEBUG="true"
```
For the VM image, I'm using Windows 10 LTSC.

I did a few tweaks on the VM such as changing the video from QXL to Virtio and CPU to Hypervisor default and the localtime tweak.

**Comment by f-fanni** [comment]
For what is worth, the same issue is present for me as well. I am running Ubuntu 18.04, same config file as the other user.

Basically if there an app (native or RDP, full screen or windowed) under the dock, the clicks (left and right) go through the dock and reach the app, whilst if there is nothing under the dock, the left click is registered as right click. 
The top bar in my case breaks only some times, so I can't really describe it.

At first I thought it was a problem with the focus, and that the app was constantly grabbing it, but it happens with any application as long as a RDP connection is active, and even more annoyingly sometimes things stay broken after closing RDP.

Anyway, we are either missing some flag, or this is a bug with xfreedp / gnome, which should be reported upstream and not here.

**Comment by Fmstrat** [comment]
Very interesting.. @f-fanni if you ever have the bug when the app is closed, it could be because `xfreerdp` is still holding the connection open (it does that for performance reasons when starting the next app. If it happens again, try a `killall xfreerdp` and see if it goes away!

**Comment by f-fanni** [comment]
Yep, that's correct, it works.

> it could be because xfreerdp is still holding the connection open

According to the upstream issue, the connection should be kept open for one minute or so, while in my case the process hangs for more than 10 minutes.

**Comment by Fmstrat** [comment]
Well, I hope they can solve it for you, unfortunately there's not a whole lot I can do since WinApps is a wrapper.
