### ISSUE TITLE
Unable to resize program window - xfce

### ISSUE THREAD

**Issue by e-belair** [Fmstrat/winapps#86]
I'm using xubuntu (with xfce) and I'm experiencing a behavior issue.
Everything works fine except that I can't resize the program window such as Excel. Every time it opens in full size.
The resize arrow does not appear when I put the mouse close to the corner. The only way I found at the moment is to slide the window close to a side border of the screen, then it is automatically resized to the half of my screen and keep its position. But If I try to move the window, it gets back to full-screen size.
Also, I can't minimize the window, when I click on minimize, the windows disappear and go back to its original position.

I tried with MULTIMON="true" but nothing changed

Is someone experiencing the same behavior?

**Comment by 0raculo** [comment]
#2 
Apparently still no fix :-(

**Comment by Fmstrat** [comment]
Hmm, it's back again, huh? So the handles don't show up for resizing, this is a FreeRDP issue (Well, all of this is, actually). If you click just inside the bottom right corner and start dragging, you can usually resize a window. It may not SHOW it resizing as you do it, but when you let go of the mouse button, it will resize.

Now, the maximize/minimize thing.. that's new. Are you using a single monitor or multiple? I haven't used xfce with WinApps yet, so there could be some conflicts going on there.

**Comment by e-belair** [comment]
What you suggested worked, but it's very hard because resizing in xfce is a bit tricky by nature.
I found an alternative on the web by using **alt + right click + drag**

I'm using a laptop connected to widescreen, but I'm not using the laptop screen, it's completely disabled.

The maximize button is working in both way (maximize and restore)
Only minimize isn't working, every time it minimizes and then going back to the previous state
I'll try to investigate on my side.

**Comment by Fmstrat** [comment]
Interesting that the alt+right-click works. Keep us posted on what you find out, or if you report anything to FreeRDP!

**Comment by rhyek** [comment]
@Fmstrat is there an issue we can track on the freerdp repo since you marked this as upstream? winapps seems great aside from the issues mentioned here, but sadly they're annoying enough that i don't see myself switching to linux just yet.
