### ISSUE TITLE
Hide Visual Studio outline window?

### ISSUE THREAD

**Issue by marcussacana** [Fmstrat/winapps#88]
As you can see the Visual Studio create 2 windows, one of them only to put a glow effect, isn't possible (even if with help of hacks) to hide it?
![image](https://user-images.githubusercontent.com/10576957/99674857-55807200-2a55-11eb-89af-1f5b6ea83343.png)

I tried debug the VS a little and looks like the VS use the DWM api to create this window, then the hook the CreateWindowEx or the ShowWindow isn't enought to prevent this, you have any hint?
Currently I only know that window have the class name `VisualStudioGlowWindow`, then maybe I can do a very hacky shit that create a thread in a loop searching for objects with this class name only to destroy it.

I'm not sure if is because of this effect, but after some few changes in the VS window, like resize, maximize or the VS popup something in a new window, the gnome don't handle very well something and just crash, closing my current session and sending me back to the login screen.

Anyway, if is or not problem of this effect I want to hide it because is a pain that black square over any program that I open.

**Comment by Fmstrat** [comment]
Can you try `RDP_FLAGS="-decorations"` in your `winapps.conf`?

**Comment by marcussacana** [comment]
No lucky, the gnome-shell crash log:
https://anonymousfiles.io/N9dYfEAg/

**Comment by Fmstrat** [comment]
Looks like this is a known FreeRDP issue: https://github.com/FreeRDP/FreeRDP/issues/4846

However it is closed, so you may want to open another one linking to that in the FreeRDP issue and link it here for anyone to connect with. Unfortunately as this is a FreeRDP issue, there's not really anything I can do on this end.
