### ISSUE TITLE
libvirt.libvirtError: unsupported configuration: Security driver model 'dac' is not available

### ISSUE THREAD

**Issue by Tiebe** [Fmstrat/winapps#9]
Security driver model 'dac' is not available.

Probably related to #5

**Comment by Tiebe** [comment]
If I try to fix this, by removing <domain> at the end of the XML file, I get
`
error: XML document failed to validate against schema: Unable to validate doc against /usr/share/libvirt/schemas/domain.rng
Extra element devices in interleave
Element domain failed to validate content

Failed. Try again? [y,n,i,f,?]: 
`

I forced it, and then fixed some bugs, but at the end I get 

` 
SeaBIOS (version 1.14.0-1)
Machine UUID ad4c4f80-e908-4b25-afe8-1e915edabf26

iPXE (http://ipxe.org) 00:03.0 CA00 PCI2.10 PnP PMM+BFF8F220+BFECF220 CA00


Booting from Hard Disk. . .
Boot failed: not a bootable disk

No bootable device

`

**Comment by Fmstrat** [comment]
Hmmm, seems unrelated. Did you mount a Windows ISO to install? The VM sample is bare, you still need to install Windows 10 into it with a valid license.

**Comment by Tiebe** [comment]
Ah I forgot about adding a ISO, but that still doesn't solve the original problem.

**Comment by Tiebe** [comment]
And it is probably related to #5, because once I run it as root, it doesn't give that error

**Comment by Tiebe** [comment]
Any update on this?

**Comment by Fmstrat** [comment]
@Tiebe The update for now is to just manually create a VM in virt-manager (https://www.linux.com/training-tutorials/create-and-run-virtual-machines-virt-manager/) and give it the appropriate RDPWindows name. At some point I will try to release separate XML files for different distros, but that's a lot to manage at the moment.

**Comment by Tiebe** [comment]
Ah okay thank you.

I'll close this for now.

**Comment by bphd** [comment]
Still here till today

**Comment by bphd** [comment]
Other solutions:
https://github.com/Fmstrat/winapps/issues/173#issuecomment-854093497
https://github.com/Fmstrat/winapps/issues/104#issuecomment-733000545
