### ISSUE TITLE
Big Problem Assumption

### ISSUE THREAD

**Issue by caryyu** [Fmstrat/winapps#91]
This project is really interesting, however, According to my several tryings on some plain-vm techniques, it turns out not all windows applications can properly run on VM-layer, especially for games, because some of those games are very replying on graphic components, such as DirectX 3D, etc; but still, this is also one of the great workarounds for linux users, thanks..

By the way, here has an example game, which you can give a try to justify: http://lyj.ttgames.net/index.html

**Comment by Fmstrat** [comment]
This is an expected behavior as RDP is not 3D accelerated, and even it it was, there would be too much latency. There is discussion ongoing of investigating elements like RemoteFX for 3D support for productivity (Fusion360, PS, etc) however it would not apply here.
