### ISSUE TITLE
Loading the VirtIO driver

### ISSUE THREAD

**Issue by Amaricso** [Fmstrat/winapps#97]
Hi

My problem is under the heading "Install the virtual machine". 

No drivers appear for me after I have selected the drive "E: \ ..." where the VirtIO driver ISO drivers are located on.

I did each step as described but i can't solve this issue by myself.

May anyone have an idea how to solve this problem?

Edit: I'm running the Ubuntu 20.04 lts version.

**Comment by jailanihar** [comment]
Hello, I had the same problem. I am running Kubuntu 20.04. I managed to solve it where in my case, I am installing Windows 10, 64 bit. So I choose "E:\amd64\w10" folder then the driver appear. Hope that helps.

**Comment by AdamLeonSmith** [comment]
Same problem with Ubuntu host and Win 10 guest.  Workaround of selecting the sub-folder helped me.

**Comment by Amaricso** [comment]
@jailanihar
@AdamLeonSmith

I tried your suggestions to select the sub-folder "E:\amd64\w10" an now it works like a charm. Thank both of you a lot for your help. :D
